apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  blocks:
    - cidr: "192.168.10.200/29" # Usable IPs: 192.168.10.201 to 192.168.10.206
  allowFirstLastIPs: "No" # Required in Cilium 1.16+ if reserving first/last IPs 
