apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: longhorn
  namespace: longhorn
spec:
  parentRefs:
    - name: gateway-internal
      namespace: gateway
  hostnames:
    - "longhorn.int.ejsadiarin.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: longhorn-frontend # default Longhorn UI service name
          namespace: longhorn
          port: 80 # default port
          weight: 1
