apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-components
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  generators:
    - git:
        repoURL: https://github.com/ejsadiarin/core-k8s-homelab.git
        revision: cluster
        directories:
          - path: cluster/infrastructure/networking/*
          - path: cluster/infrastructure/storage/*
          - path: cluster/infrastructure/controllers/*
          - exclude: true
            path: cluster/infrastructure/storage/csi-driver-nfs
          - exclude: true
            path: cluster/infrastructure/storage/csi-driver-smb
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        type: infrastructure
    spec:
      project: infrastructure
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/ejsadiarin/core-k8s-homelab.git
        targetRevision: cluster
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
          - ApplyOutOfSyncOnly=true
          - Replace=false
          - IgnoreMissingTemplate=true
