// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budget.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addExpenseTag = `-- name: AddExpenseTag :exec

INSERT INTO budget_expense_tags (expense_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddExpenseTagParams struct {
	ExpenseID uuid.UUID `json:"expense_id"`
	TagID     uuid.UUID `json:"tag_id"`
}

// Expense Tags
func (q *Queries) AddExpenseTag(ctx context.Context, arg AddExpenseTagParams) error {
	_, err := q.db.Exec(ctx, addExpenseTag, arg.ExpenseID, arg.TagID)
	return err
}

const createCategory = `-- name: CreateCategory :one

INSERT INTO budget_categories (
    name, color, icon
) VALUES (
    $1, $2, $3
)
RETURNING id, name, color, icon, created_at
`

type CreateCategoryParams struct {
	Name  string      `json:"name"`
	Color pgtype.Text `json:"color"`
	Icon  pgtype.Text `json:"icon"`
}

// Categories
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (BudgetCategory, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Color, arg.Icon)
	var i BudgetCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const createExpense = `-- name: CreateExpense :one

INSERT INTO budget_expenses (
    description, amount, currency, category_id, expense_date, notes
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, description, amount, currency, category_id, expense_date, created_at, updated_at, notes
`

type CreateExpenseParams struct {
	Description string         `json:"description"`
	Amount      pgtype.Numeric `json:"amount"`
	Currency    pgtype.Text    `json:"currency"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	ExpenseDate pgtype.Date    `json:"expense_date"`
	Notes       pgtype.Text    `json:"notes"`
}

// Expenses
func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (BudgetExpense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.CategoryID,
		arg.ExpenseDate,
		arg.Notes,
	)
	var i BudgetExpense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.CategoryID,
		&i.ExpenseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one

INSERT INTO budget_tags (
    name, color
) VALUES (
    $1, $2
)
RETURNING id, name, color, created_at
`

type CreateTagParams struct {
	Name  string      `json:"name"`
	Color pgtype.Text `json:"color"`
}

// Tags
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (BudgetTag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Name, arg.Color)
	var i BudgetTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM budget_categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM budget_expenses
WHERE id = $1
`

func (q *Queries) DeleteExpense(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpense, id)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM budget_tags
WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, color, icon, created_at FROM budget_categories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (BudgetCategory, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i BudgetCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const getCategorySpending = `-- name: GetCategorySpending :many
SELECT
    c.id,
    c.name,
    c.color,
    COALESCE(SUM(e.amount), 0::numeric) as total_amount,
    COUNT(e.id) as transaction_count
FROM budget_expenses e
JOIN budget_categories c ON e.category_id = c.id
WHERE
    ($1::date IS NULL OR e.expense_date >= $1::date)
    AND ($2::date IS NULL OR e.expense_date <= $2::date)
GROUP BY c.id, c.name, c.color
ORDER BY total_amount DESC
`

type GetCategorySpendingParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetCategorySpendingRow struct {
	ID               uuid.UUID   `json:"id"`
	Name             string      `json:"name"`
	Color            pgtype.Text `json:"color"`
	TotalAmount      interface{} `json:"total_amount"`
	TransactionCount int64       `json:"transaction_count"`
}

func (q *Queries) GetCategorySpending(ctx context.Context, arg GetCategorySpendingParams) ([]GetCategorySpendingRow, error) {
	rows, err := q.db.Query(ctx, getCategorySpending, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategorySpendingRow{}
	for rows.Next() {
		var i GetCategorySpendingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.TotalAmount,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailySpending = `-- name: GetDailySpending :many
SELECT
    expense_date,
    COALESCE(SUM(amount), 0::numeric) as total_amount,
    COUNT(id) as transaction_count
FROM budget_expenses
WHERE
    ($1::date IS NULL OR expense_date >= $1::date)
    AND ($2::date IS NULL OR expense_date <= $2::date)
GROUP BY expense_date
ORDER BY expense_date ASC
`

type GetDailySpendingParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetDailySpendingRow struct {
	ExpenseDate      pgtype.Date `json:"expense_date"`
	TotalAmount      interface{} `json:"total_amount"`
	TransactionCount int64       `json:"transaction_count"`
}

func (q *Queries) GetDailySpending(ctx context.Context, arg GetDailySpendingParams) ([]GetDailySpendingRow, error) {
	rows, err := q.db.Query(ctx, getDailySpending, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailySpendingRow{}
	for rows.Next() {
		var i GetDailySpendingRow
		if err := rows.Scan(&i.ExpenseDate, &i.TotalAmount, &i.TransactionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpense = `-- name: GetExpense :one
SELECT id, description, amount, currency, category_id, expense_date, created_at, updated_at, notes FROM budget_expenses
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetExpense(ctx context.Context, id uuid.UUID) (BudgetExpense, error) {
	row := q.db.QueryRow(ctx, getExpense, id)
	var i BudgetExpense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.CategoryID,
		&i.ExpenseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
	)
	return i, err
}

const getExpenseTags = `-- name: GetExpenseTags :many
SELECT t.id, t.name, t.color, t.created_at
FROM budget_tags t
JOIN budget_expense_tags et ON t.id = et.tag_id
WHERE et.expense_id = $1
`

func (q *Queries) GetExpenseTags(ctx context.Context, expenseID uuid.UUID) ([]BudgetTag, error) {
	rows, err := q.db.Query(ctx, getExpenseTags, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetTag{}
	for rows.Next() {
		var i BudgetTag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpensesByDateRange = `-- name: GetExpensesByDateRange :many

SELECT id, description, amount, currency, category_id, expense_date, created_at, updated_at, notes FROM budget_expenses
WHERE expense_date BETWEEN $1 AND $2
ORDER BY expense_date DESC
`

type GetExpensesByDateRangeParams struct {
	ExpenseDate   pgtype.Date `json:"expense_date"`
	ExpenseDate_2 pgtype.Date `json:"expense_date_2"`
}

// Statistics
func (q *Queries) GetExpensesByDateRange(ctx context.Context, arg GetExpensesByDateRangeParams) ([]BudgetExpense, error) {
	rows, err := q.db.Query(ctx, getExpensesByDateRange, arg.ExpenseDate, arg.ExpenseDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetExpense{}
	for rows.Next() {
		var i BudgetExpense
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.ExpenseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlySpending = `-- name: GetMonthlySpending :many
SELECT
    TO_CHAR(expense_date, 'YYYY-MM') as month,
    COALESCE(SUM(amount), 0::numeric) as total_amount,
    COUNT(id) as transaction_count
FROM budget_expenses
GROUP BY month
ORDER BY month DESC
LIMIT 12
`

type GetMonthlySpendingRow struct {
	Month            string      `json:"month"`
	TotalAmount      interface{} `json:"total_amount"`
	TransactionCount int64       `json:"transaction_count"`
}

func (q *Queries) GetMonthlySpending(ctx context.Context) ([]GetMonthlySpendingRow, error) {
	rows, err := q.db.Query(ctx, getMonthlySpending)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlySpendingRow{}
	for rows.Next() {
		var i GetMonthlySpendingRow
		if err := rows.Scan(&i.Month, &i.TotalAmount, &i.TransactionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTag = `-- name: GetTag :one
SELECT id, name, color, created_at FROM budget_tags
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTag(ctx context.Context, id uuid.UUID) (BudgetTag, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i BudgetTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalSpending = `-- name: GetTotalSpending :one
SELECT
    COALESCE(SUM(amount), 0::numeric) as total_amount,
    COUNT(id) as transaction_count
FROM budget_expenses
WHERE
    ($1::date IS NULL OR expense_date >= $1::date)
    AND ($2::date IS NULL OR expense_date <= $2::date)
`

type GetTotalSpendingParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetTotalSpendingRow struct {
	TotalAmount      interface{} `json:"total_amount"`
	TransactionCount int64       `json:"transaction_count"`
}

func (q *Queries) GetTotalSpending(ctx context.Context, arg GetTotalSpendingParams) (GetTotalSpendingRow, error) {
	row := q.db.QueryRow(ctx, getTotalSpending, arg.StartDate, arg.EndDate)
	var i GetTotalSpendingRow
	err := row.Scan(&i.TotalAmount, &i.TransactionCount)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, color, icon, created_at FROM budget_categories
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]BudgetCategory, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetCategory{}
	for rows.Next() {
		var i BudgetCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Icon,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenses = `-- name: ListExpenses :many
SELECT e.id, e.description, e.amount, e.currency, e.category_id, e.expense_date, e.created_at, e.updated_at, e.notes, c.name as category_name, c.color as category_color, c.icon as category_icon
FROM budget_expenses e
LEFT JOIN budget_categories c ON e.category_id = c.id
WHERE
    ($1::uuid IS NULL OR e.category_id = $1)
    AND ($2::date IS NULL OR e.expense_date >= $2::date)
    AND ($3::date IS NULL OR e.expense_date <= $3::date)
ORDER BY e.expense_date DESC, e.created_at DESC
`

type ListExpensesParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

type ListExpensesRow struct {
	ID            uuid.UUID        `json:"id"`
	Description   string           `json:"description"`
	Amount        pgtype.Numeric   `json:"amount"`
	Currency      pgtype.Text      `json:"currency"`
	CategoryID    pgtype.UUID      `json:"category_id"`
	ExpenseDate   pgtype.Date      `json:"expense_date"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	Notes         pgtype.Text      `json:"notes"`
	CategoryName  pgtype.Text      `json:"category_name"`
	CategoryColor pgtype.Text      `json:"category_color"`
	CategoryIcon  pgtype.Text      `json:"category_icon"`
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]ListExpensesRow, error) {
	rows, err := q.db.Query(ctx, listExpenses, arg.CategoryID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpensesRow{}
	for rows.Next() {
		var i ListExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.ExpenseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Notes,
			&i.CategoryName,
			&i.CategoryColor,
			&i.CategoryIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, color, created_at FROM budget_tags
ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]BudgetTag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetTag{}
	for rows.Next() {
		var i BudgetTag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllExpenseTags = `-- name: RemoveAllExpenseTags :exec
DELETE FROM budget_expense_tags
WHERE expense_id = $1
`

func (q *Queries) RemoveAllExpenseTags(ctx context.Context, expenseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeAllExpenseTags, expenseID)
	return err
}

const removeExpenseTag = `-- name: RemoveExpenseTag :exec
DELETE FROM budget_expense_tags
WHERE expense_id = $1 AND tag_id = $2
`

type RemoveExpenseTagParams struct {
	ExpenseID uuid.UUID `json:"expense_id"`
	TagID     uuid.UUID `json:"tag_id"`
}

func (q *Queries) RemoveExpenseTag(ctx context.Context, arg RemoveExpenseTagParams) error {
	_, err := q.db.Exec(ctx, removeExpenseTag, arg.ExpenseID, arg.TagID)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE budget_categories
SET
    name = COALESCE($2, name),
    color = COALESCE($3, color),
    icon = COALESCE($4, icon)
WHERE id = $1
RETURNING id, name, color, icon, created_at
`

type UpdateCategoryParams struct {
	ID    uuid.UUID   `json:"id"`
	Name  pgtype.Text `json:"name"`
	Color pgtype.Text `json:"color"`
	Icon  pgtype.Text `json:"icon"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (BudgetCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.Icon,
	)
	var i BudgetCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
	)
	return i, err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE budget_expenses
SET
    description = COALESCE($2, description),
    amount = COALESCE($3, amount),
    currency = COALESCE($4, currency),
    category_id = COALESCE($5, category_id),
    expense_date = COALESCE($6, expense_date),
    notes = COALESCE($7, notes),
    updated_at = NOW()
WHERE id = $1
RETURNING id, description, amount, currency, category_id, expense_date, created_at, updated_at, notes
`

type UpdateExpenseParams struct {
	ID          uuid.UUID      `json:"id"`
	Description pgtype.Text    `json:"description"`
	Amount      pgtype.Numeric `json:"amount"`
	Currency    pgtype.Text    `json:"currency"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	ExpenseDate pgtype.Date    `json:"expense_date"`
	Notes       pgtype.Text    `json:"notes"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (BudgetExpense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.CategoryID,
		arg.ExpenseDate,
		arg.Notes,
	)
	var i BudgetExpense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.CategoryID,
		&i.ExpenseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
	)
	return i, err
}

const updateTag = `-- name: UpdateTag :one
UPDATE budget_tags
SET
    name = COALESCE($2, name),
    color = COALESCE($3, color)
WHERE id = $1
RETURNING id, name, color, created_at
`

type UpdateTagParams struct {
	ID    uuid.UUID   `json:"id"`
	Name  pgtype.Text `json:"name"`
	Color pgtype.Text `json:"color"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (BudgetTag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.ID, arg.Name, arg.Color)
	var i BudgetTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}
