// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: income.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countIncomes = `-- name: CountIncomes :one
SELECT COUNT(*) FROM budget_incomes
WHERE
    user_id = $1
    AND ($2::text IS NULL OR recurring_type = $2::text)
    AND ($3::date IS NULL OR date >= $3::date)
    AND ($4::date IS NULL OR date <= $4::date)
`

type CountIncomesParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	RecurringType pgtype.Text `json:"recurring_type"`
	StartDate     pgtype.Date `json:"start_date"`
	EndDate       pgtype.Date `json:"end_date"`
}

func (q *Queries) CountIncomes(ctx context.Context, arg CountIncomesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIncomes,
		arg.UserID,
		arg.RecurringType,
		arg.StartDate,
		arg.EndDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIncome = `-- name: CreateIncome :one

INSERT INTO budget_incomes (
    amount, currency, date, description, recurring_type, start_date, end_date, user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, amount, currency, date, description, recurring_type, start_date, created_at, updated_at, end_date
`

type CreateIncomeParams struct {
	Amount        pgtype.Numeric `json:"amount"`
	Currency      pgtype.Text    `json:"currency"`
	Date          pgtype.Date    `json:"date"`
	Description   pgtype.Text    `json:"description"`
	RecurringType pgtype.Text    `json:"recurring_type"`
	StartDate     pgtype.Date    `json:"start_date"`
	EndDate       pgtype.Date    `json:"end_date"`
	UserID        uuid.UUID      `json:"user_id"`
}

// Incomes
func (q *Queries) CreateIncome(ctx context.Context, arg CreateIncomeParams) (BudgetIncome, error) {
	row := q.db.QueryRow(ctx, createIncome,
		arg.Amount,
		arg.Currency,
		arg.Date,
		arg.Description,
		arg.RecurringType,
		arg.StartDate,
		arg.EndDate,
		arg.UserID,
	)
	var i BudgetIncome
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Date,
		&i.Description,
		&i.RecurringType,
		&i.StartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndDate,
	)
	return i, err
}

const deleteIncome = `-- name: DeleteIncome :exec
DELETE FROM budget_incomes
WHERE id = $1 AND user_id = $2
`

type DeleteIncomeParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteIncome(ctx context.Context, arg DeleteIncomeParams) error {
	_, err := q.db.Exec(ctx, deleteIncome, arg.ID, arg.UserID)
	return err
}

const getAllOneTimeIncomeToDate = `-- name: GetAllOneTimeIncomeToDate :one
SELECT COALESCE(SUM(amount), 0::numeric) as total_amount
FROM budget_incomes
WHERE
    ($1::uuid IS NULL OR user_id = $1)
    AND recurring_type IS NULL
    AND date <= $2::date
`

type GetAllOneTimeIncomeToDateParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Date   pgtype.Date `json:"date"`
}

func (q *Queries) GetAllOneTimeIncomeToDate(ctx context.Context, arg GetAllOneTimeIncomeToDateParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getAllOneTimeIncomeToDate, arg.UserID, arg.Date)
	var total_amount interface{}
	err := row.Scan(&total_amount)
	return total_amount, err
}

const getAllRecurringIncomeRules = `-- name: GetAllRecurringIncomeRules :many
SELECT id, user_id, amount, currency, date, description, recurring_type, start_date, created_at, updated_at, end_date FROM budget_incomes
WHERE
    ($1::uuid IS NULL OR user_id = $1)
    AND recurring_type IN ('daily', 'weekly', 'monthly')
    AND start_date <= $2::date
    AND (end_date IS NULL OR end_date >= $2::date)
ORDER BY start_date
`

type GetAllRecurringIncomeRulesParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Date   pgtype.Date `json:"date"`
}

func (q *Queries) GetAllRecurringIncomeRules(ctx context.Context, arg GetAllRecurringIncomeRulesParams) ([]BudgetIncome, error) {
	rows, err := q.db.Query(ctx, getAllRecurringIncomeRules, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetIncome{}
	for rows.Next() {
		var i BudgetIncome
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Currency,
			&i.Date,
			&i.Description,
			&i.RecurringType,
			&i.StartDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTotalExpensesToDate = `-- name: GetAllTotalExpensesToDate :one
SELECT COALESCE(SUM(amount), 0::numeric) as total_amount
FROM budget_expenses
WHERE
    ($1::uuid IS NULL OR user_id = $1)
    AND expense_date <= $2::date
`

type GetAllTotalExpensesToDateParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Date   pgtype.Date `json:"date"`
}

func (q *Queries) GetAllTotalExpensesToDate(ctx context.Context, arg GetAllTotalExpensesToDateParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getAllTotalExpensesToDate, arg.UserID, arg.Date)
	var total_amount interface{}
	err := row.Scan(&total_amount)
	return total_amount, err
}

const getIncome = `-- name: GetIncome :one
SELECT id, user_id, amount, currency, date, description, recurring_type, start_date, created_at, updated_at, end_date FROM budget_incomes
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetIncomeParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetIncome(ctx context.Context, arg GetIncomeParams) (BudgetIncome, error) {
	row := q.db.QueryRow(ctx, getIncome, arg.ID, arg.UserID)
	var i BudgetIncome
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Date,
		&i.Description,
		&i.RecurringType,
		&i.StartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndDate,
	)
	return i, err
}

const getIncomeByID = `-- name: GetIncomeByID :one
SELECT id, user_id, amount, currency, date, description, recurring_type, start_date, created_at, updated_at, end_date FROM budget_incomes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetIncomeByID(ctx context.Context, id uuid.UUID) (BudgetIncome, error) {
	row := q.db.QueryRow(ctx, getIncomeByID, id)
	var i BudgetIncome
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Date,
		&i.Description,
		&i.RecurringType,
		&i.StartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndDate,
	)
	return i, err
}

const getOneTimeIncomeToDate = `-- name: GetOneTimeIncomeToDate :one

SELECT COALESCE(SUM(amount), 0::numeric) as total_amount
FROM budget_incomes
WHERE
    user_id = $1
    AND recurring_type IS NULL
    AND date <= $2
`

type GetOneTimeIncomeToDateParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Date   pgtype.Date `json:"date"`
}

// Budget Remaining Calculation Queries
// These queries fetch raw data; proration logic is handled in the application layer
func (q *Queries) GetOneTimeIncomeToDate(ctx context.Context, arg GetOneTimeIncomeToDateParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getOneTimeIncomeToDate, arg.UserID, arg.Date)
	var total_amount interface{}
	err := row.Scan(&total_amount)
	return total_amount, err
}

const getRecurringIncomeRules = `-- name: GetRecurringIncomeRules :many
SELECT id, user_id, amount, currency, date, description, recurring_type, start_date, created_at, updated_at, end_date FROM budget_incomes
WHERE
    user_id = $1
    AND recurring_type IN ('daily', 'weekly', 'monthly')
    AND start_date <= $2
    AND (end_date IS NULL OR end_date >= $2)
ORDER BY start_date
`

type GetRecurringIncomeRulesParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	StartDate pgtype.Date `json:"start_date"`
}

func (q *Queries) GetRecurringIncomeRules(ctx context.Context, arg GetRecurringIncomeRulesParams) ([]BudgetIncome, error) {
	rows, err := q.db.Query(ctx, getRecurringIncomeRules, arg.UserID, arg.StartDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetIncome{}
	for rows.Next() {
		var i BudgetIncome
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Currency,
			&i.Date,
			&i.Description,
			&i.RecurringType,
			&i.StartDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalExpensesToDate = `-- name: GetTotalExpensesToDate :one
SELECT COALESCE(SUM(amount), 0::numeric) as total_amount
FROM budget_expenses
WHERE
    user_id = $1
    AND expense_date <= $2
`

type GetTotalExpensesToDateParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	ExpenseDate pgtype.Date `json:"expense_date"`
}

func (q *Queries) GetTotalExpensesToDate(ctx context.Context, arg GetTotalExpensesToDateParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getTotalExpensesToDate, arg.UserID, arg.ExpenseDate)
	var total_amount interface{}
	err := row.Scan(&total_amount)
	return total_amount, err
}

const listAllIncomes = `-- name: ListAllIncomes :many
SELECT i.id, i.user_id, i.amount, i.currency, i.date, i.description, i.recurring_type, i.start_date, i.created_at, i.updated_at, i.end_date, u.email as user_email
FROM budget_incomes i
JOIN users u ON i.user_id = u.id
WHERE
    ($1::uuid IS NULL OR i.user_id = $1)
    AND ($2::text IS NULL OR i.recurring_type = $2::text)
    AND ($3::date IS NULL OR i.date >= $3::date)
    AND ($4::date IS NULL OR i.date <= $4::date)
ORDER BY i.date DESC, i.created_at DESC
`

type ListAllIncomesParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	RecurringType pgtype.Text `json:"recurring_type"`
	StartDate     pgtype.Date `json:"start_date"`
	EndDate       pgtype.Date `json:"end_date"`
}

type ListAllIncomesRow struct {
	ID            uuid.UUID        `json:"id"`
	UserID        uuid.UUID        `json:"user_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	Currency      pgtype.Text      `json:"currency"`
	Date          pgtype.Date      `json:"date"`
	Description   pgtype.Text      `json:"description"`
	RecurringType pgtype.Text      `json:"recurring_type"`
	StartDate     pgtype.Date      `json:"start_date"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	EndDate       pgtype.Date      `json:"end_date"`
	UserEmail     string           `json:"user_email"`
}

func (q *Queries) ListAllIncomes(ctx context.Context, arg ListAllIncomesParams) ([]ListAllIncomesRow, error) {
	rows, err := q.db.Query(ctx, listAllIncomes,
		arg.UserID,
		arg.RecurringType,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllIncomesRow{}
	for rows.Next() {
		var i ListAllIncomesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Currency,
			&i.Date,
			&i.Description,
			&i.RecurringType,
			&i.StartDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndDate,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomes = `-- name: ListIncomes :many
SELECT id, user_id, amount, currency, date, description, recurring_type, start_date, created_at, updated_at, end_date FROM budget_incomes
WHERE
    user_id = $1
    AND ($2::text IS NULL OR recurring_type = $2::text)
    AND ($3::date IS NULL OR date >= $3::date)
    AND ($4::date IS NULL OR date <= $4::date)
ORDER BY date DESC, created_at DESC
`

type ListIncomesParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	RecurringType pgtype.Text `json:"recurring_type"`
	StartDate     pgtype.Date `json:"start_date"`
	EndDate       pgtype.Date `json:"end_date"`
}

func (q *Queries) ListIncomes(ctx context.Context, arg ListIncomesParams) ([]BudgetIncome, error) {
	rows, err := q.db.Query(ctx, listIncomes,
		arg.UserID,
		arg.RecurringType,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetIncome{}
	for rows.Next() {
		var i BudgetIncome
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Currency,
			&i.Date,
			&i.Description,
			&i.RecurringType,
			&i.StartDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomesPaginated = `-- name: ListIncomesPaginated :many
SELECT id, user_id, amount, currency, date, description, recurring_type, start_date, created_at, updated_at, end_date FROM budget_incomes
WHERE
    user_id = $1
    AND ($4::text IS NULL OR recurring_type = $4::text)
    AND ($5::date IS NULL OR date >= $5::date)
    AND ($6::date IS NULL OR date <= $6::date)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListIncomesPaginatedParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
	RecurringType pgtype.Text `json:"recurring_type"`
	StartDate     pgtype.Date `json:"start_date"`
	EndDate       pgtype.Date `json:"end_date"`
}

func (q *Queries) ListIncomesPaginated(ctx context.Context, arg ListIncomesPaginatedParams) ([]BudgetIncome, error) {
	rows, err := q.db.Query(ctx, listIncomesPaginated,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.RecurringType,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetIncome{}
	for rows.Next() {
		var i BudgetIncome
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Currency,
			&i.Date,
			&i.Description,
			&i.RecurringType,
			&i.StartDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncome = `-- name: UpdateIncome :one
UPDATE budget_incomes
SET
    amount = COALESCE($3, amount),
    currency = COALESCE($4, currency),
    date = COALESCE($5, date),
    description = COALESCE($6, description),
    recurring_type = COALESCE($7, recurring_type),
    start_date = COALESCE($8, start_date),
    end_date = COALESCE($9, end_date),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, amount, currency, date, description, recurring_type, start_date, created_at, updated_at, end_date
`

type UpdateIncomeParams struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	Amount        pgtype.Numeric `json:"amount"`
	Currency      pgtype.Text    `json:"currency"`
	Date          pgtype.Date    `json:"date"`
	Description   pgtype.Text    `json:"description"`
	RecurringType pgtype.Text    `json:"recurring_type"`
	StartDate     pgtype.Date    `json:"start_date"`
	EndDate       pgtype.Date    `json:"end_date"`
}

func (q *Queries) UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (BudgetIncome, error) {
	row := q.db.QueryRow(ctx, updateIncome,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.Currency,
		arg.Date,
		arg.Description,
		arg.RecurringType,
		arg.StartDate,
		arg.EndDate,
	)
	var i BudgetIncome
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Currency,
		&i.Date,
		&i.Description,
		&i.RecurringType,
		&i.StartDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EndDate,
	)
	return i, err
}
