// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateHealthHistory(ctx context.Context, arg CreateHealthHistoryParams) (ServiceHealthHistory, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	DeleteService(ctx context.Context, id uuid.UUID) error
	GetAllServicesStats(ctx context.Context) (GetAllServicesStatsRow, error)
	GetService(ctx context.Context, id uuid.UUID) (Service, error)
	GetServiceHistory(ctx context.Context, arg GetServiceHistoryParams) ([]ServiceHealthHistory, error)
	GetServiceStats24h(ctx context.Context, serviceID pgtype.UUID) (GetServiceStats24hRow, error)
	GetServiceStats30d(ctx context.Context, serviceID pgtype.UUID) (GetServiceStats30dRow, error)
	GetServiceStats7d(ctx context.Context, serviceID pgtype.UUID) (GetServiceStats7dRow, error)
	ListActiveServicesForHealthCheck(ctx context.Context) ([]ListActiveServicesForHealthCheckRow, error)
	ListServices(ctx context.Context) ([]ListServicesRow, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
}

var _ Querier = (*Queries)(nil)
