apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgBniIm609fPUCq9cOtmU5ZLTIDeLmr/NTXDXKJ5wwqd4NgHXsS9CxURDNrgR9b6SUsmE2ge23V4536pjGN5+QgEnQpID57OGTfyQXYkBqMqCB+6rxIAA7JA/WKElwse+UzdK/ZLyLqhOEEU7mqy1CNREh6Xyfa+rmm3/7VEJUMDukVKFMPRqQrM4EwEhf7ozVHG/NnsEncHU8sZADug5j76flBej5MWnEGx/RL6ymkeRgVQ5CN+1ZvJnl/rAYCepgo0XwEg70O0j38cnVxdA+osBIhYwXr7tG8ObKOClwHCU2njpOGVznx30bWcbDREoz0d1cfy2yKYDcbvu4E3tRa2mLoa8gv196iVgXZaMcEDBsc0Q91pidCEAzaF2jI6fu2PBlbHn59QALqytaCShF5sSG/9T5tEXUncrYjEj1+coI2hhyzai5SWClyr7Z4GNesjo6+8O52F3XQX2pYNlhM2qeNgt8LZjM9CJuGgnSFGMBVxVzmGNxBORyEJVUsxCzLuzb6DvIYsg7GrcWohix7Q+dwHOXnA21UZ1H5mv3wKFCZwQT0L1Fd8wqteLGdkkMfCeXnJtDr+dwv54NvG/Xl9aO2KlYd1kXJTJWv89KSry0iNiuNO2jXg8+XF68DvDLol67A3ifwoUujDCwLs+NdjoF4NV+GQpXO/tOrMZfAfRvmsY13f26pVDssYfNCqJkbvDIZKt6tbvc/BrLVyYrAtvinag6rRg/YJ0kCO+kr6jl8Hp75Ar+zUdBx80LqHYq78xO5fdz6i8tt6ApNJuqhZrc2TdVYGcPGUIm13Z8hnV08AKUmvqvkSC3fXquZqrdZZhOrtkQmuACbcDoWR0rBTMHGrIRr21VbyWdrwtm+sn1ww36rjUj79awpJfqnaNArH8TcRMshYXJryWOcAs1hVsjbbom+QdliQdW5q/vGx
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: tunnel-credentials
      namespace: cloudflared
    type: Opaque
