#!/bin/bash

sudo mkdir -p /mnt/ColdStorage
sudo mkdir -p /mnt/Storage1
sudo mkdir -p /mnt/Backups
sudo mkdir -p /mnt/Storage2

sudo mount -L "ColdStorage" /mnt/ColdStorage
sudo mount -L "Storage1" /mnt/Storage1
sudo mount -L "Backups" /mnt/Backups
sudo mount -L "Storage2" /mnt/Storage2
