apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - ns.yaml
  - ../../common/cilium-network-policies

namespace: it-tools

labels:
  - pairs:
      app.kubernetes.io/name: it-tools
      app.kubernetes.io/part-of: web-apps
      app.kubernetes.io/managed-by: argocd