---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bday

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  # - ../../common/cilium-network-policies

labels:
  - pairs:
      app.kubernetes.io/name: bday-hannah
      app.kubernetes.io/part-of: web-apps
      app.kubernetes.io/managed-by: argocd
