--
-- PostgreSQL database dump
--

\restrict QHMMZxAfphBX9eEM0CF9QekXEuhmnlflORMxkwX1baMagUAgtlBMyualf1JCWE9

-- Dumped from database version 17.7 (bdd1736)
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: budget_categories; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.budget_categories (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(100) NOT NULL,
    color character varying(7),
    icon character varying(50),
    created_at timestamp without time zone DEFAULT now(),
    user_id uuid NOT NULL,
    category_type character varying(10),
    CONSTRAINT budget_categories_category_type_check CHECK (((category_type)::text = ANY ((ARRAY['need'::character varying, 'want'::character varying, 'savings'::character varying])::text[])))
);


ALTER TABLE public.budget_categories OWNER TO neondb_owner;

--
-- Name: budget_expense_tags; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.budget_expense_tags (
    expense_id uuid NOT NULL,
    tag_id uuid NOT NULL
);


ALTER TABLE public.budget_expense_tags OWNER TO neondb_owner;

--
-- Name: budget_expenses; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.budget_expenses (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    description text NOT NULL,
    amount numeric(10,2) NOT NULL,
    currency character varying(3) DEFAULT 'USD'::character varying,
    category_id uuid,
    expense_date date NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    notes text,
    user_id uuid NOT NULL,
    recurring_type text,
    start_date date,
    end_date date,
    CONSTRAINT budget_expenses_recurring_start_date_check CHECK (((recurring_type IS NULL) OR (start_date IS NOT NULL))),
    CONSTRAINT budget_expenses_recurring_type_check CHECK (((recurring_type = ANY (ARRAY['daily'::text, 'weekly'::text, 'monthly'::text, 'yearly'::text])) OR (recurring_type IS NULL)))
);


ALTER TABLE public.budget_expenses OWNER TO neondb_owner;

--
-- Name: budget_incomes; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.budget_incomes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    amount numeric(10,2) NOT NULL,
    currency character varying(3) DEFAULT 'USD'::character varying,
    date date NOT NULL,
    description text,
    recurring_type character varying(10),
    start_date date,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    end_date date,
    CONSTRAINT budget_incomes_recurring_start_date_check CHECK (((recurring_type IS NULL) OR (start_date IS NOT NULL))),
    CONSTRAINT budget_incomes_recurring_type_check CHECK ((((recurring_type)::text = ANY ((ARRAY['daily'::character varying, 'weekly'::character varying, 'monthly'::character varying])::text[])) OR (recurring_type IS NULL)))
);


ALTER TABLE public.budget_incomes OWNER TO neondb_owner;

--
-- Name: budget_tags; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.budget_tags (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(100) NOT NULL,
    color character varying(7),
    created_at timestamp without time zone DEFAULT now(),
    user_id uuid NOT NULL
);


ALTER TABLE public.budget_tags OWNER TO neondb_owner;

--
-- Name: category_budgets; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.category_budgets (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    category_id uuid NOT NULL,
    month date NOT NULL,
    budget_amount numeric(12,2) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.category_budgets OWNER TO neondb_owner;

--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.goose_db_version OWNER TO neondb_owner;

--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: savings_goals; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.savings_goals (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    name character varying(100) NOT NULL,
    target_amount numeric(12,2) NOT NULL,
    current_amount numeric(12,2) DEFAULT 0,
    deadline date,
    icon character varying(50),
    color character varying(7),
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.savings_goals OWNER TO neondb_owner;

--
-- Name: service_health_history; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.service_health_history (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    service_id uuid,
    status character varying(20) NOT NULL,
    response_time integer,
    status_code integer,
    error_message text,
    checked_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.service_health_history OWNER TO neondb_owner;

--
-- Name: services; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.services (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    url character varying(500) NOT NULL,
    icon character varying(50),
    description text,
    service_type character varying(100),
    health_check_interval integer DEFAULT 60,
    health_check_method character varying(10) DEFAULT 'GET'::character varying,
    expected_status_codes integer[] DEFAULT '{200,204}'::integer[],
    timeout integer DEFAULT 5000,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    is_active boolean DEFAULT true
);


ALTER TABLE public.services OWNER TO neondb_owner;

--
-- Name: sessions; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.sessions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    token_hash character varying(64) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.sessions OWNER TO neondb_owner;

--
-- Name: users; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email character varying(255) NOT NULL,
    password_hash text,
    role character varying(20) DEFAULT 'user'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['guest'::character varying, 'user'::character varying, 'admin'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO neondb_owner;

--
-- Data for Name: budget_categories; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.budget_categories (id, name, color, icon, created_at, user_id, category_type) FROM stdin;
49785996-a6c2-4be2-81da-8534ae7cdc56	food	#f66151		2026-02-03 17:28:12.388111	e2d1870e-8d2a-49c7-9198-bca125470747	\N
89a24011-867e-4b03-885f-4dd9e5befc57	transportation	#62a0ea		2026-02-03 17:31:31.987725	e2d1870e-8d2a-49c7-9198-bca125470747	\N
cf2b1a78-56e4-4ce4-aec6-b99d588443b5	entertainment	#f6d32d		2026-02-03 17:34:40.360337	e2d1870e-8d2a-49c7-9198-bca125470747	\N
fdd10dbf-c121-423d-85ce-c4872ddc335f	transportation	#f8e45c		2026-02-04 08:41:56.125633	ff378c7b-e785-4994-8be3-a5586228f1d5	\N
b476a6c0-5ab7-4393-838c-ce8a0e1cb9b1	needs	#99c1f1		2026-02-04 08:45:34.558975	ff378c7b-e785-4994-8be3-a5586228f1d5	\N
7b4afac9-928f-4c89-9fe9-4993e2b07fac	gifts	#f66151		2026-02-04 08:46:22.892196	ff378c7b-e785-4994-8be3-a5586228f1d5	\N
21c9277f-3cc4-458b-8d99-ec6f86bd722b	emergency	#ffffff		2026-02-04 11:26:18.862722	ff378c7b-e785-4994-8be3-a5586228f1d5	\N
a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	food	#26a269		2026-02-04 05:10:09.661507	ff378c7b-e785-4994-8be3-a5586228f1d5	\N
\.


--
-- Data for Name: budget_expense_tags; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.budget_expense_tags (expense_id, tag_id) FROM stdin;
37360746-1922-43da-9f5e-287b9f0281d7	2ce784a8-2880-4c54-8eb5-8309cad686ae
37360746-1922-43da-9f5e-287b9f0281d7	0381f4a1-2422-4868-87eb-4728d2c4e0e4
73f22af3-d219-45da-9519-fd1cd0542cd2	2ce784a8-2880-4c54-8eb5-8309cad686ae
73f22af3-d219-45da-9519-fd1cd0542cd2	0381f4a1-2422-4868-87eb-4728d2c4e0e4
ad717a49-4394-48ff-9b9b-26a32310722a	2ce784a8-2880-4c54-8eb5-8309cad686ae
ad717a49-4394-48ff-9b9b-26a32310722a	0381f4a1-2422-4868-87eb-4728d2c4e0e4
77aef580-080b-4c49-ac71-ea9e57d94ce2	0381f4a1-2422-4868-87eb-4728d2c4e0e4
77aef580-080b-4c49-ac71-ea9e57d94ce2	2ce784a8-2880-4c54-8eb5-8309cad686ae
b197fe5d-4627-4c53-aac3-5c360b766566	2ce784a8-2880-4c54-8eb5-8309cad686ae
b197fe5d-4627-4c53-aac3-5c360b766566	bf59e1b0-c3a2-4a13-81ff-fb8345960103
8887c8da-eb3f-4756-b983-f1752763f97e	97ca9ef3-07a0-46b1-902e-dcc082a8df79
4aa1ba44-9d20-4dcf-8abd-de7bda6fe278	97ca9ef3-07a0-46b1-902e-dcc082a8df79
aa82cb77-9843-477b-8f81-20d1a93f7307	bf59e1b0-c3a2-4a13-81ff-fb8345960103
0b9c8d51-e31a-4563-8320-6f40f07f5478	bf59e1b0-c3a2-4a13-81ff-fb8345960103
333b6b57-174b-48d9-bbed-169fdd0db6eb	bf59e1b0-c3a2-4a13-81ff-fb8345960103
5f93a85b-04a2-4760-8dc0-2dbe3aaf0a8f	bf59e1b0-c3a2-4a13-81ff-fb8345960103
991e734f-0dbf-45ed-836a-56c9ca98a658	bf59e1b0-c3a2-4a13-81ff-fb8345960103
f3f37c19-ea67-44d9-9424-1e5a72b6ff72	bf59e1b0-c3a2-4a13-81ff-fb8345960103
81e7645e-63b0-4f39-9800-91f3cc1c6bb3	bf59e1b0-c3a2-4a13-81ff-fb8345960103
89bde243-9598-4c2f-b46c-58e8ffff391f	0381f4a1-2422-4868-87eb-4728d2c4e0e4
89bde243-9598-4c2f-b46c-58e8ffff391f	2ce784a8-2880-4c54-8eb5-8309cad686ae
53eed6ad-3bbf-4b6f-baa5-c2c549000bf6	2ce784a8-2880-4c54-8eb5-8309cad686ae
671a3cb3-19dc-4860-b48a-a057cd4f171c	bf59e1b0-c3a2-4a13-81ff-fb8345960103
671a3cb3-19dc-4860-b48a-a057cd4f171c	0381f4a1-2422-4868-87eb-4728d2c4e0e4
671a3cb3-19dc-4860-b48a-a057cd4f171c	2ce784a8-2880-4c54-8eb5-8309cad686ae
ab558cd2-b99b-4244-981a-d963c58b9a48	2ce784a8-2880-4c54-8eb5-8309cad686ae
01b19294-10c3-469d-82a3-ca160beee8cd	bf59e1b0-c3a2-4a13-81ff-fb8345960103
7e58585a-07a3-4490-81b7-939525de0486	bf59e1b0-c3a2-4a13-81ff-fb8345960103
dd7f4c80-c49d-4a97-937f-3fea6763c89f	bf59e1b0-c3a2-4a13-81ff-fb8345960103
a1df3596-68c5-4ea6-a417-7907c60e7279	bf59e1b0-c3a2-4a13-81ff-fb8345960103
9aeaa2d6-8553-48ba-8290-6ee4b3aa9d41	bf59e1b0-c3a2-4a13-81ff-fb8345960103
8fe0073c-cefc-4b70-9988-acf85c51869c	bf59e1b0-c3a2-4a13-81ff-fb8345960103
d2390525-73a1-4b97-9852-41b33bcfd832	2ce784a8-2880-4c54-8eb5-8309cad686ae
d2390525-73a1-4b97-9852-41b33bcfd832	0381f4a1-2422-4868-87eb-4728d2c4e0e4
1b319b48-266a-4996-8cc6-42c122a6e918	2ce784a8-2880-4c54-8eb5-8309cad686ae
1b319b48-266a-4996-8cc6-42c122a6e918	bf59e1b0-c3a2-4a13-81ff-fb8345960103
df96804b-9965-44ea-9c2b-750601ddbee6	bf59e1b0-c3a2-4a13-81ff-fb8345960103
438d6d13-e221-4f9c-836a-c85b4e0b8285	bf59e1b0-c3a2-4a13-81ff-fb8345960103
438d6d13-e221-4f9c-836a-c85b4e0b8285	0381f4a1-2422-4868-87eb-4728d2c4e0e4
438d6d13-e221-4f9c-836a-c85b4e0b8285	2ce784a8-2880-4c54-8eb5-8309cad686ae
7d87ef1d-618d-46cf-ba93-bc76095947b8	0381f4a1-2422-4868-87eb-4728d2c4e0e4
7d87ef1d-618d-46cf-ba93-bc76095947b8	2ce784a8-2880-4c54-8eb5-8309cad686ae
f6c3e254-47f4-4d8f-99b0-2cfd9cf2a97d	bf59e1b0-c3a2-4a13-81ff-fb8345960103
f6c3e254-47f4-4d8f-99b0-2cfd9cf2a97d	0381f4a1-2422-4868-87eb-4728d2c4e0e4
f6c3e254-47f4-4d8f-99b0-2cfd9cf2a97d	2ce784a8-2880-4c54-8eb5-8309cad686ae
6eabba22-83f8-4eb4-8a47-14653748b95b	2ce784a8-2880-4c54-8eb5-8309cad686ae
7786793f-9487-4ece-9c38-58a69810fcc5	bf59e1b0-c3a2-4a13-81ff-fb8345960103
7786793f-9487-4ece-9c38-58a69810fcc5	0381f4a1-2422-4868-87eb-4728d2c4e0e4
7786793f-9487-4ece-9c38-58a69810fcc5	2ce784a8-2880-4c54-8eb5-8309cad686ae
9f284cc6-6c52-4d90-a1b8-b2df1a5e8428	bf59e1b0-c3a2-4a13-81ff-fb8345960103
9f284cc6-6c52-4d90-a1b8-b2df1a5e8428	2ce784a8-2880-4c54-8eb5-8309cad686ae
0eb6c9c0-fec8-4990-95e0-33ac8293df85	0381f4a1-2422-4868-87eb-4728d2c4e0e4
0eb6c9c0-fec8-4990-95e0-33ac8293df85	bf59e1b0-c3a2-4a13-81ff-fb8345960103
0eb6c9c0-fec8-4990-95e0-33ac8293df85	2ce784a8-2880-4c54-8eb5-8309cad686ae
c24a225e-d188-4467-b476-4814ade6a5f6	2ce784a8-2880-4c54-8eb5-8309cad686ae
ef7f4ae0-b97c-49bd-b13e-491a8f73f9db	2ce784a8-2880-4c54-8eb5-8309cad686ae
ef7f4ae0-b97c-49bd-b13e-491a8f73f9db	0381f4a1-2422-4868-87eb-4728d2c4e0e4
b4151ab7-9f2f-4da4-addf-c293aeaaffdc	2ce784a8-2880-4c54-8eb5-8309cad686ae
d7ff95d6-d4fb-4024-8f6c-77737a4d48ef	bf59e1b0-c3a2-4a13-81ff-fb8345960103
3f299ef7-c135-48f1-a688-4fd613f95ece	2ce784a8-2880-4c54-8eb5-8309cad686ae
3f299ef7-c135-48f1-a688-4fd613f95ece	0381f4a1-2422-4868-87eb-4728d2c4e0e4
8038c5a5-4ed3-43dd-b73f-177dd1539345	2ce784a8-2880-4c54-8eb5-8309cad686ae
8038c5a5-4ed3-43dd-b73f-177dd1539345	0381f4a1-2422-4868-87eb-4728d2c4e0e4
e9e87c60-7b74-465f-a54c-d992d8c28ad0	2ce784a8-2880-4c54-8eb5-8309cad686ae
3eb1236f-37fd-457b-9f2c-3bdbf8f00e79	bf59e1b0-c3a2-4a13-81ff-fb8345960103
3eb1236f-37fd-457b-9f2c-3bdbf8f00e79	97ca9ef3-07a0-46b1-902e-dcc082a8df79
4cf1e898-551b-4c47-a133-235146e590a0	97ca9ef3-07a0-46b1-902e-dcc082a8df79
4cf1e898-551b-4c47-a133-235146e590a0	2ce784a8-2880-4c54-8eb5-8309cad686ae
4cf1e898-551b-4c47-a133-235146e590a0	bf59e1b0-c3a2-4a13-81ff-fb8345960103
1d6834cb-eb0c-46c8-93f1-479c98fe6db2	2ce784a8-2880-4c54-8eb5-8309cad686ae
b16350e3-00c5-4044-9bc9-8d8b62df81c9	2ce784a8-2880-4c54-8eb5-8309cad686ae
ac5042ae-e413-489f-9931-b1b468a2cf68	2ce784a8-2880-4c54-8eb5-8309cad686ae
ac5042ae-e413-489f-9931-b1b468a2cf68	bf59e1b0-c3a2-4a13-81ff-fb8345960103
222311a5-ae05-46d4-8623-0be9616dedf0	0381f4a1-2422-4868-87eb-4728d2c4e0e4
222311a5-ae05-46d4-8623-0be9616dedf0	2ce784a8-2880-4c54-8eb5-8309cad686ae
9693375e-8630-4b56-a62d-073f6fcef0d9	bf59e1b0-c3a2-4a13-81ff-fb8345960103
1e8b4d7a-1df5-4f4e-9e87-e18400321007	2ce784a8-2880-4c54-8eb5-8309cad686ae
03a7410e-d163-41c1-9bc8-0f120378c605	2ce784a8-2880-4c54-8eb5-8309cad686ae
03a7410e-d163-41c1-9bc8-0f120378c605	bf59e1b0-c3a2-4a13-81ff-fb8345960103
d921762d-313d-45f3-81f4-0ac5265dc560	bf59e1b0-c3a2-4a13-81ff-fb8345960103
9a914593-e499-49b3-9f18-9d44b90ced9f	2ce784a8-2880-4c54-8eb5-8309cad686ae
9a914593-e499-49b3-9f18-9d44b90ced9f	bf59e1b0-c3a2-4a13-81ff-fb8345960103
88f07c95-9a75-4ee5-a974-15a5a1b9c0c1	2ce784a8-2880-4c54-8eb5-8309cad686ae
88f07c95-9a75-4ee5-a974-15a5a1b9c0c1	bf59e1b0-c3a2-4a13-81ff-fb8345960103
95a7c969-ac3f-42d5-be8b-37af21b0f728	2ce784a8-2880-4c54-8eb5-8309cad686ae
95a7c969-ac3f-42d5-be8b-37af21b0f728	bf59e1b0-c3a2-4a13-81ff-fb8345960103
3f53f58d-461d-4dd3-93c4-cd56c83ad8a8	bf59e1b0-c3a2-4a13-81ff-fb8345960103
3cc1829e-dc5a-46da-b72f-225c9388d594	bf59e1b0-c3a2-4a13-81ff-fb8345960103
05073abf-c24c-4e60-a265-77b28d5338d5	2ce784a8-2880-4c54-8eb5-8309cad686ae
05073abf-c24c-4e60-a265-77b28d5338d5	bf59e1b0-c3a2-4a13-81ff-fb8345960103
c5bf0076-c54f-477d-88c2-de41bf69324c	2ce784a8-2880-4c54-8eb5-8309cad686ae
c5bf0076-c54f-477d-88c2-de41bf69324c	bf59e1b0-c3a2-4a13-81ff-fb8345960103
0454dd81-a3d5-427b-9a86-bca77c3d584f	bf59e1b0-c3a2-4a13-81ff-fb8345960103
734badf3-4bb6-4ff8-b3a2-e34c032554ee	2ce784a8-2880-4c54-8eb5-8309cad686ae
d54a6ad9-8c1e-4b11-b4c9-e52c89aeb184	2ce784a8-2880-4c54-8eb5-8309cad686ae
d54a6ad9-8c1e-4b11-b4c9-e52c89aeb184	bf59e1b0-c3a2-4a13-81ff-fb8345960103
58838a68-64d4-49ec-948d-391231aaa6ca	2ce784a8-2880-4c54-8eb5-8309cad686ae
58838a68-64d4-49ec-948d-391231aaa6ca	bf59e1b0-c3a2-4a13-81ff-fb8345960103
ea5db378-32bf-4652-8cd9-a8fe2c358cdf	bf59e1b0-c3a2-4a13-81ff-fb8345960103
ea5db378-32bf-4652-8cd9-a8fe2c358cdf	2ce784a8-2880-4c54-8eb5-8309cad686ae
bfdc4ce5-7252-4b8e-8ff2-8eccf813bd9b	2ce784a8-2880-4c54-8eb5-8309cad686ae
329c3049-4753-4c5c-afde-b4feafdb19e5	2ce784a8-2880-4c54-8eb5-8309cad686ae
aa1659ab-cb78-4cbc-a087-113b5558d9cf	2ce784a8-2880-4c54-8eb5-8309cad686ae
06f4a2e9-10cd-456a-b1c9-ec32fe66f95e	bf59e1b0-c3a2-4a13-81ff-fb8345960103
f04ffc7d-3fb4-4f04-8bb9-408cf805e183	2ce784a8-2880-4c54-8eb5-8309cad686ae
cf20f280-b01d-4d9b-8808-86883fc53f48	2ce784a8-2880-4c54-8eb5-8309cad686ae
d5e24917-a84d-40c1-a95d-222083323a5a	2ce784a8-2880-4c54-8eb5-8309cad686ae
5a10b7a4-19f0-439f-86a4-e5e4ab28954f	2ce784a8-2880-4c54-8eb5-8309cad686ae
\.


--
-- Data for Name: budget_expenses; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.budget_expenses (id, description, amount, currency, category_id, expense_date, created_at, updated_at, notes, user_id, recurring_type, start_date, end_date) FROM stdin;
60146e0f-fa35-482a-a298-b832eb0d5378	Aperitif	909.00	PHP	49785996-a6c2-4be2-81da-8534ae7cdc56	2026-02-02	2026-02-03 17:30:29.807923	2026-02-03 17:30:29.807923	\N	e2d1870e-8d2a-49c7-9198-bca125470747	\N	\N	\N
4f34c4f5-a67a-410e-9de0-3bfec71de2f4	Grab - two stop kingswood + MOA	272.00	PHP	\N	2026-02-02	2026-02-03 17:39:04.167673	2026-02-03 17:39:04.167673	two stop	e2d1870e-8d2a-49c7-9198-bca125470747	\N	\N	\N
c0608801-b685-4400-a608-ee62cc53231f	asdf	123.00	PHP	\N	2026-02-04	2026-02-04 05:20:46.691664	2026-02-04 05:20:46.691664	\N	045ce9f1-aa0c-4d01-b284-75b445c1c27a	\N	\N	\N
ab558cd2-b99b-4244-981a-d963c58b9a48	flowers order for valentines	2000.00	PHP	7b4afac9-928f-4c89-9fe9-4993e2b07fac	2026-01-28	2026-02-04 11:54:22.225018	2026-02-04 11:55:55.933841	pota mahal +500 SF fok ampota	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
37360746-1922-43da-9f5e-287b9f0281d7	Flowers for bday	300.00	PHP	7b4afac9-928f-4c89-9fe9-4993e2b07fac	2026-02-02	2026-02-04 05:13:16.133119	2026-02-04 08:46:49.104863	bday flowers	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
73f22af3-d219-45da-9519-fd1cd0542cd2	Aperitif	909.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-02-02	2026-02-04 05:11:48.274111	2026-02-04 08:47:30.371285	bday celeb meow meow	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
ad717a49-4394-48ff-9b9b-26a32310722a	Grab - two stop kingswood + MOA	272.00	PHP	fdd10dbf-c121-423d-85ce-c4872ddc335f	2026-02-02	2026-02-04 05:12:35.157161	2026-02-04 08:59:13.858151	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
77aef580-080b-4c49-ac71-ea9e57d94ce2	Dongwon samgyupsal	1102.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-01-15	2026-02-04 09:46:46.348929	2026-02-04 09:46:46.348929	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
b197fe5d-4627-4c53-aac3-5c360b766566	Grab to meow meow	150.00	PHP	fdd10dbf-c121-423d-85ce-c4872ddc335f	2026-01-15	2026-02-04 09:49:39.484639	2026-02-04 09:50:23.947617	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
01b19294-10c3-469d-82a3-ca160beee8cd	food idk again	69.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-01-29	2026-02-04 11:56:39.123712	2026-02-04 11:56:39.123712	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
7e58585a-07a3-4490-81b7-939525de0486	chicken honey mustard	119.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-01-29	2026-02-04 11:57:23.474169	2026-02-04 11:57:23.474169	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
dd7f4c80-c49d-4a97-937f-3fea6763c89f	milky mango graham at agno lol	89.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-01-29	2026-02-04 11:55:36.580983	2026-02-04 11:57:52.467902	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
a1df3596-68c5-4ea6-a417-7907c60e7279	goodmunch - rosemary chicken	150.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-01-30	2026-02-04 11:59:10.456551	2026-02-04 11:59:10.456551	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
3f299ef7-c135-48f1-a688-4fd613f95ece	Spice Table food	1210.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-02-02	2026-02-04 12:14:58.803571	2026-02-04 12:14:58.803571	seafood paella - 640\nlinguine truffle pasta - 470	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
8887c8da-eb3f-4756-b983-f1752763f97e	biscoff latte from mood coffee 	139.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-01-21	2026-02-04 11:31:23.188463	2026-02-04 11:31:23.188463	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
4aa1ba44-9d20-4dcf-8abd-de7bda6fe278	again biscoff latte from mood coffee	139.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-01-22	2026-02-04 11:32:18.082598	2026-02-04 11:32:18.082598	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
aa82cb77-9843-477b-8f81-20d1a93f7307	some food at agno	110.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-01-22	2026-02-04 11:32:51.990667	2026-02-04 11:32:51.990667	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
0b9c8d51-e31a-4563-8320-6f40f07f5478	FOOD again i think	225.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-01-22	2026-02-04 11:33:46.556406	2026-02-04 11:34:23.578445	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
9aeaa2d6-8553-48ba-8290-6ee4b3aa9d41	milky mango graham again	89.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-01-30	2026-02-04 11:59:40.927991	2026-02-04 11:59:40.927991	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
333b6b57-174b-48d9-bbed-169fdd0db6eb	idk	60.00	PHP	b476a6c0-5ab7-4393-838c-ce8a0e1cb9b1	2026-01-22	2026-02-04 11:34:11.028781	2026-02-04 11:34:32.645529	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
5f93a85b-04a2-4760-8dc0-2dbe3aaf0a8f	food?grab? idk	110.00	PHP	b476a6c0-5ab7-4393-838c-ce8a0e1cb9b1	2026-01-22	2026-02-04 11:35:43.998544	2026-02-04 11:35:43.998544	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
991e734f-0dbf-45ed-836a-56c9ca98a658	SALMON ONIGIRI	65.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-01-23	2026-02-04 11:43:20.706175	2026-02-04 11:43:20.706175	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
f3f37c19-ea67-44d9-9424-1e5a72b6ff72	SALMON ONIGIRI again	65.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-01-24	2026-02-04 11:47:19.422204	2026-02-04 11:47:41.330439	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
81e7645e-63b0-4f39-9800-91f3cc1c6bb3	UNIQLO - knitted polo shirt	1500.00	PHP	7b4afac9-928f-4c89-9fe9-4993e2b07fac	2026-01-24	2026-02-04 11:48:49.310231	2026-02-04 11:49:10.211676	so goooooooooooood quality polo shirt	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
89bde243-9598-4c2f-b46c-58e8ffff391f	samgyup or hotpot	1150.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-01-27	2026-02-04 11:51:15.039472	2026-02-04 11:51:15.039472	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
53eed6ad-3bbf-4b6f-baa5-c2c549000bf6	people's place fine dining food	2000.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-01-24	2026-02-04 11:51:52.378932	2026-02-04 11:51:52.378932	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
671a3cb3-19dc-4860-b48a-a057cd4f171c	FOOD IDK	250.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-01-28	2026-02-04 11:53:32.719231	2026-02-04 11:53:32.719231	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
8fe0073c-cefc-4b70-9988-acf85c51869c	food?	85.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-01-30	2026-02-04 12:00:27.684316	2026-02-04 12:00:27.684316	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
d2390525-73a1-4b97-9852-41b33bcfd832	grab to meow meow	100.00	PHP	fdd10dbf-c121-423d-85ce-c4872ddc335f	2026-01-30	2026-02-04 12:01:19.200857	2026-02-04 12:01:19.200857	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
1b319b48-266a-4996-8cc6-42c122a6e918	condoms hehe	220.00	PHP	21c9277f-3cc4-458b-8d99-ec6f86bd722b	2026-01-30	2026-02-04 12:02:27.913773	2026-02-04 12:02:27.913773	INVISIBLE MAN	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
df96804b-9965-44ea-9c2b-750601ddbee6	lumpiang shanghai w rice - uncle johns	70.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-01-30	2026-02-04 12:02:59.962486	2026-02-04 12:02:59.962486	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
438d6d13-e221-4f9c-836a-c85b4e0b8285	grab two stop	515.00	PHP	fdd10dbf-c121-423d-85ce-c4872ddc335f	2026-01-30	2026-02-04 12:04:26.561557	2026-02-04 12:06:19.436636	kingswood then home	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
7d87ef1d-618d-46cf-ba93-bc76095947b8	jolibee after drinking	350.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-01-30	2026-02-04 12:05:02.729682	2026-02-04 12:06:27.109072	libre	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
f6c3e254-47f4-4d8f-99b0-2cfd9cf2a97d	grab to ayala for bday vpop	260.00	PHP	fdd10dbf-c121-423d-85ce-c4872ddc335f	2026-01-23	2026-02-04 11:42:45.189215	2026-02-04 12:07:20.570698	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
6eabba22-83f8-4eb4-8a47-14653748b95b	Print SCOPE	50.00	PHP	21c9277f-3cc4-458b-8d99-ec6f86bd722b	2026-01-16	2026-02-04 11:25:58.614552	2026-02-04 12:07:34.311212	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
7786793f-9487-4ece-9c38-58a69810fcc5	grab to meow meow	99.00	PHP	fdd10dbf-c121-423d-85ce-c4872ddc335f	2026-01-16	2026-02-04 11:28:50.639032	2026-02-04 12:07:39.724255	idk i forgot lol	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
9f284cc6-6c52-4d90-a1b8-b2df1a5e8428	Angkas transpo	318.00	PHP	fdd10dbf-c121-423d-85ce-c4872ddc335f	2026-01-15	2026-02-04 09:48:23.729899	2026-02-04 12:07:48.448802	from kingswood to home	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
0eb6c9c0-fec8-4990-95e0-33ac8293df85	Grab to Home	500.00	PHP	fdd10dbf-c121-423d-85ce-c4872ddc335f	2026-01-16	2026-02-04 11:24:48.715789	2026-02-04 12:07:59.892669	with meow meow	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
c24a225e-d188-4467-b476-4814ade6a5f6	mono mansion - photobooth	300.00	PHP	7b4afac9-928f-4c89-9fe9-4993e2b07fac	2026-02-02	2026-02-04 12:12:13.021589	2026-02-04 12:12:13.021589	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
ef7f4ae0-b97c-49bd-b13e-491a8f73f9db	ridesss - the drop tower MOA	240.00	PHP	7b4afac9-928f-4c89-9fe9-4993e2b07fac	2026-02-02	2026-02-04 12:10:06.354742	2026-02-04 12:12:20.798623	for 2 (DATE WITH MEOW MEOW)	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
b4151ab7-9f2f-4da4-addf-c293aeaaffdc	grab to Parqal	100.00	PHP	fdd10dbf-c121-423d-85ce-c4872ddc335f	2026-02-02	2026-02-04 12:13:00.326196	2026-02-04 12:13:00.326196	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
d7ff95d6-d4fb-4024-8f6c-77737a4d48ef	AHMAD TEA - 100pcs at The Marketplace	366.00	PHP	b476a6c0-5ab7-4393-838c-ce8a0e1cb9b1	2026-02-02	2026-02-04 12:13:44.198704	2026-02-04 12:13:44.198704	may reimburse na 400 tho hehehe	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
8038c5a5-4ed3-43dd-b73f-177dd1539345	Grab two stop kingswood then home	706.00	PHP	fdd10dbf-c121-423d-85ce-c4872ddc335f	2026-02-02	2026-02-04 12:15:34.036668	2026-02-04 12:15:34.036668	from Parqal	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
e9e87c60-7b74-465f-a54c-d992d8c28ad0	Starbucks coffee w libre	400.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-02-02	2026-02-04 12:16:12.376216	2026-02-04 12:16:12.376216	i libre her, the salted caramel na di salted	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
3eb1236f-37fd-457b-9f2c-3bdbf8f00e79	kohico biscoff latte + 10pcs pandesal	205.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-02-05	2026-02-06 07:06:38.616719	2026-02-06 07:06:38.616719	155 for the biscoff latte	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
4cf1e898-551b-4c47-a133-235146e590a0	2 coffee at mood coffee	250.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-02-06	2026-02-06 07:07:49.053998	2026-02-06 07:07:49.053998	americano + biscoff latte - 89 + 139	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
1d6834cb-eb0c-46c8-93f1-479c98fe6db2	grab to meow meow	150.00	PHP	fdd10dbf-c121-423d-85ce-c4872ddc335f	2026-02-06	2026-02-06 17:16:42.914092	2026-02-06 17:16:42.914092	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
b16350e3-00c5-4044-9bc9-8d8b62df81c9	mcdo fries n sundae	150.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-02-06	2026-02-06 17:17:24.59632	2026-02-06 17:17:24.59632	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
ac5042ae-e413-489f-9931-b1b468a2cf68	grab indrive to home	650.00	PHP	fdd10dbf-c121-423d-85ce-c4872ddc335f	2026-02-06	2026-02-06 17:19:24.599087	2026-02-06 17:19:24.599087	fok kawit cavitex\n\noverall: 522 (base) + 39 (toll) + 89 (cavitex kawit exit toll)	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
222311a5-ae05-46d4-8623-0be9616dedf0	AIRBNB Valentines getaway date	2671.00	PHP	7b4afac9-928f-4c89-9fe9-4993e2b07fac	2026-02-08	2026-02-08 06:59:22.99067	2026-02-08 06:59:22.99067	meow meow	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
78d88575-a722-437d-b16e-a88c85c0e6e0	class suspension (-500 to fri weekly)	500.00	PHP	\N	2026-01-09	2026-02-08 15:19:08.008087	2026-02-08 15:19:08.008087	backfill	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
2d405a92-2611-4f21-a03d-65229adb64cb	didnt attend class (backfill)	500.00	PHP	\N	2026-02-04	2026-02-08 15:21:05.058969	2026-02-08 15:21:05.058969	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
6ed5038d-778c-49ab-a1e8-ef780fd0a3eb	didnt attend class (backfill)	500.00	PHP	\N	2026-01-14	2026-02-08 15:21:21.637266	2026-02-08 15:21:21.637266	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
9693375e-8630-4b56-a62d-073f6fcef0d9	didnt attend class (backfill)	500.00	PHP	\N	2026-01-31	2026-02-08 15:23:46.955474	2026-02-08 15:23:46.955474	from inom kasi lmao (went home 3am)	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
e781a1d9-3088-476c-91fc-65926cbe2185	misc (to match actual budget) - backfill	1129.00	PHP	\N	2026-01-01	2026-02-08 15:26:04.167405	2026-02-08 15:26:20.347586	actual budget balance	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
1e8b4d7a-1df5-4f4e-9e87-e18400321007	owala - 32oz tumbler (shoppee)	844.00	PHP	7b4afac9-928f-4c89-9fe9-4993e2b07fac	2026-02-08	2026-02-08 14:18:09.76255	2026-02-09 02:47:12.831431	cute dog 32oz	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
03a7410e-d163-41c1-9bc8-0f120378c605	ole chicken + truffle (with extra chicken both)	400.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-02-11	2026-02-11 14:30:50.615093	2026-02-11 14:30:50.615093	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
d921762d-313d-45f3-81f4-0ac5265dc560	double cheese yen	140.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-02-11	2026-02-11 14:31:30.136017	2026-02-11 14:31:30.136017	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
9a914593-e499-49b3-9f18-9d44b90ced9f	takoyaki	150.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-02-11	2026-02-11 14:31:50.724684	2026-02-11 14:31:50.724684	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
88f07c95-9a75-4ee5-a974-15a5a1b9c0c1	her need 10	10.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-02-11	2026-02-11 14:32:16.93268	2026-02-11 14:32:16.93268	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
95a7c969-ac3f-42d5-be8b-37af21b0f728	grab 2 two stop	754.00	PHP	fdd10dbf-c121-423d-85ce-c4872ddc335f	2026-02-11	2026-02-11 14:33:25.954616	2026-02-11 14:33:25.954616	3 toll gates wtf (582 + 39 + 45 + 89)	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
3f53f58d-461d-4dd3-93c4-cd56c83ad8a8	sausage with rice	120.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-02-12	2026-02-12 14:28:45.166404	2026-02-12 14:28:45.166404	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
3cc1829e-dc5a-46da-b72f-225c9388d594	something i forgot idk	30.00	PHP	\N	2026-02-12	2026-02-12 14:30:22.874285	2026-02-12 14:30:22.874285	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
05073abf-c24c-4e60-a265-77b28d5338d5	pandesal 4pcs	20.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-02-12	2026-02-12 14:31:01.568534	2026-02-12 14:31:01.568534	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
c5bf0076-c54f-477d-88c2-de41bf69324c	cards - deluxe blitz or something	129.00	PHP	7b4afac9-928f-4c89-9fe9-4993e2b07fac	2026-02-12	2026-02-12 14:32:08.81331	2026-02-12 14:32:08.81331	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
0454dd81-a3d5-427b-9a86-bca77c3d584f	tuition fee 2nd installment payment	45915.00	PHP	b476a6c0-5ab7-4393-838c-ce8a0e1cb9b1	2026-02-12	2026-02-12 14:32:33.306224	2026-02-12 14:48:25.373	7709075298076216503237	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
734badf3-4bb6-4ff8-b3a2-e34c032554ee	for valentines	170.00	PHP	7b4afac9-928f-4c89-9fe9-4993e2b07fac	2026-02-13	2026-02-16 10:37:39.393055	2026-02-16 10:37:39.393055	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
d54a6ad9-8c1e-4b11-b4c9-e52c89aeb184	pandesal 4pcs	20.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-02-13	2026-02-16 10:35:55.957702	2026-02-16 10:37:54.780029	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
58838a68-64d4-49ec-948d-391231aaa6ca	cs	295.00	PHP	b476a6c0-5ab7-4393-838c-ce8a0e1cb9b1	2026-02-13	2026-02-16 10:38:54.139305	2026-02-16 10:38:54.139305	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
ea5db378-32bf-4652-8cd9-a8fe2c358cdf	VALENTINES: beautiful bahay drinks parqal	420.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-02-14	2026-02-16 10:40:28.125268	2026-02-16 10:40:42.432945	230 - lemonade drink, 190 - tea drink	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
bfdc4ce5-7252-4b8e-8ff2-8eccf813bd9b	VALENTINES: mary grace lunch	1500.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-02-14	2026-02-16 10:42:28.672666	2026-02-16 10:42:28.672666	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
329c3049-4753-4c5c-afde-b4feafdb19e5	VALENTINES: dinner at Bon Pho	1450.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-02-14	2026-02-16 10:43:04.831789	2026-02-16 10:43:19.572035	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
aa1659ab-cb78-4cbc-a087-113b5558d9cf	VALENTINES: 2 massage at nuat thai	1400.00	PHP	7b4afac9-928f-4c89-9fe9-4993e2b07fac	2026-02-14	2026-02-16 10:41:21.430482	2026-02-16 10:43:28.23832	700 each - head shoulder back massage	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
06f4a2e9-10cd-456a-b1c9-ec32fe66f95e	VALENTINES: my joyride going home 	200.00	PHP	fdd10dbf-c121-423d-85ce-c4872ddc335f	2026-02-14	2026-02-16 10:43:55.462298	2026-02-16 10:44:06.166135	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
f04ffc7d-3fb4-4f04-8bb9-408cf805e183	grab	50.00	PHP	fdd10dbf-c121-423d-85ce-c4872ddc335f	2026-02-15	2026-02-16 10:44:47.865792	2026-02-16 10:44:47.865792	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
cf20f280-b01d-4d9b-8808-86883fc53f48	groceries	1388.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-02-15	2026-02-16 10:44:30.018536	2026-02-16 10:45:10.37636	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
d5e24917-a84d-40c1-a95d-222083323a5a	grab two stop	125.00	PHP	fdd10dbf-c121-423d-85ce-c4872ddc335f	2026-02-15	2026-02-16 10:45:38.960969	2026-02-16 10:45:38.960969	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
5a10b7a4-19f0-439f-86a4-e5e4ab28954f	seoul galbi lunch	730.00	PHP	a2e3c8b4-b2f0-4e55-8d81-9cb5875c3669	2026-02-16	2026-02-16 10:46:16.459891	2026-02-16 10:46:16.459891	\N	ff378c7b-e785-4994-8be3-a5586228f1d5	\N	\N	\N
\.


--
-- Data for Name: budget_incomes; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.budget_incomes (id, user_id, amount, currency, date, description, recurring_type, start_date, created_at, updated_at, end_date) FROM stdin;
90fc5368-5361-4a3a-b7e3-eb58895d68d2	ff378c7b-e785-4994-8be3-a5586228f1d5	500.00	PHP	2026-02-08	from mama beth	\N	\N	2026-02-08 05:45:51.563275	2026-02-08 05:45:51.563275	\N
ad436905-06cf-4ca6-a621-0e133d68387b	ff378c7b-e785-4994-8be3-a5586228f1d5	10000.00	PHP	2026-01-23	birthday gift	\N	\N	2026-02-08 06:56:02.802463	2026-02-08 06:56:02.802463	\N
22a61332-771f-4fbb-bd4d-aeda5df86b12	ff378c7b-e785-4994-8be3-a5586228f1d5	13000.00	PHP	2025-12-25	christmas gift from mom and mama beth + ading	\N	\N	2026-02-08 06:55:17.249396	2026-02-08 06:56:48.794199	\N
4caf80eb-2013-4fd2-b93e-34a924891535	ff378c7b-e785-4994-8be3-a5586228f1d5	500.00	PHP	2026-01-08	Thurs weekly allowance	weekly	2026-01-08	2026-02-08 14:45:48.384827	2026-02-08 14:45:48.384827	2026-04-09
d075d34d-14a9-4a5f-9384-6893f21b7b31	ff378c7b-e785-4994-8be3-a5586228f1d5	500.00	PHP	2026-01-09	Fri weekly allowance	weekly	2026-01-09	2026-02-08 14:48:50.263118	2026-02-08 14:48:50.263118	2026-04-10
16c6baec-b742-4020-9e4a-2a895be46d55	ff378c7b-e785-4994-8be3-a5586228f1d5	54255.00	PHP	2026-01-01	Bank (backfill)	\N	\N	2026-02-08 14:55:20.961268	2026-02-08 14:55:20.961268	\N
97ed939a-4bda-47f3-acb5-59006e0c4705	ff378c7b-e785-4994-8be3-a5586228f1d5	1654.00	PHP	2026-01-01	Gcash (backfill)	\N	\N	2026-02-08 15:05:01.57324	2026-02-08 15:05:01.57324	\N
c63736c7-932e-4738-8f1a-f2ce31ab19dc	ff378c7b-e785-4994-8be3-a5586228f1d5	500.00	PHP	2026-01-07	Wed weekly allowance	weekly	2026-01-07	2026-02-08 15:20:15.368262	2026-02-08 15:20:15.368262	2026-04-08
07a53266-f693-4171-9124-12bec3aa41f1	ff378c7b-e785-4994-8be3-a5586228f1d5	500.00	PHP	2026-01-10	Sat weekly allowance	weekly	2026-01-10	2026-02-08 15:22:08.945977	2026-02-08 15:22:08.945977	2026-04-11
d216c24f-d025-447c-aa79-f74c1c137893	ff378c7b-e785-4994-8be3-a5586228f1d5	300.00	PHP	2026-02-11	meow meow contrib for grab	\N	\N	2026-02-11 14:33:56.36932	2026-02-11 14:33:56.36932	\N
840747b4-ebc1-4b97-ae41-b6c91a268fa3	ff378c7b-e785-4994-8be3-a5586228f1d5	173.00	PHP	2026-02-11	meow meow contrib toll fee awwwwwww	\N	\N	2026-02-11 14:34:14.081307	2026-02-11 14:34:14.081307	\N
6f2a93ba-704a-4afd-86d4-8314452ca337	ff378c7b-e785-4994-8be3-a5586228f1d5	55.00	PHP	2026-02-11	reduce fee for the grab	\N	\N	2026-02-11 14:34:50.331776	2026-02-11 14:34:50.331776	\N
d2be2306-666f-4ec4-a25b-7944d78832dc	ff378c7b-e785-4994-8be3-a5586228f1d5	2000.00	PHP	2026-02-15	meow meow contrib for valentines staycation	\N	\N	2026-02-16 10:47:19.735892	2026-02-16 10:47:19.735892	\N
\.


--
-- Data for Name: budget_tags; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.budget_tags (id, name, color, created_at, user_id) FROM stdin;
0381f4a1-2422-4868-87eb-4728d2c4e0e4	gala	#f6f5f4	2026-02-04 08:43:13.917912	ff378c7b-e785-4994-8be3-a5586228f1d5
97ca9ef3-07a0-46b1-902e-dcc082a8df79	coffee	#b5835a	2026-02-04 08:44:35.483049	ff378c7b-e785-4994-8be3-a5586228f1d5
bf59e1b0-c3a2-4a13-81ff-fb8345960103	self	#f9f06b	2026-02-04 08:45:24.522861	ff378c7b-e785-4994-8be3-a5586228f1d5
2ce784a8-2880-4c54-8eb5-8309cad686ae	her	#8b5cf6	2026-02-04 05:10:59.840442	ff378c7b-e785-4994-8be3-a5586228f1d5
\.


--
-- Data for Name: category_budgets; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.category_budgets (id, user_id, category_id, month, budget_amount, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: goose_db_version; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.goose_db_version (id, version_id, is_applied, tstamp) FROM stdin;
1	0	t	2026-02-03 17:04:15.027515
2	1	t	2026-02-03 17:11:53.661032
3	2	t	2026-02-03 17:11:54.985672
4	3	t	2026-02-04 04:43:53.197643
5	4	t	2026-02-04 04:54:55.739822
6	5	t	2026-02-07 11:53:12.740162
7	6	t	2026-02-08 08:03:57.196379
8	7	t	2026-02-08 09:38:50.382307
9	8	t	2026-02-10 15:07:27.56963
10	9	t	2026-02-16 13:53:10.944807
11	10	t	2026-02-16 13:53:12.510156
12	11	t	2026-02-16 13:53:13.68206
\.


--
-- Data for Name: savings_goals; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.savings_goals (id, user_id, name, target_amount, current_amount, deadline, icon, color, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: service_health_history; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.service_health_history (id, service_id, status, response_time, status_code, error_message, checked_at) FROM stdin;
\.


--
-- Data for Name: services; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.services (id, name, url, icon, description, service_type, health_check_interval, health_check_method, expected_status_codes, timeout, created_at, updated_at, is_active) FROM stdin;
\.


--
-- Data for Name: sessions; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.sessions (id, user_id, token_hash, expires_at, created_at) FROM stdin;
1584c57f-6301-4959-9b82-ca087a831ad8	ff378c7b-e785-4994-8be3-a5586228f1d5	ded80180fecf8b1889931cc0e60ef4916550fd60dcbc6ca87802d185ac1d7b6a	2026-03-12 16:17:43.711492	2026-02-10 08:17:43.966091
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

COPY public.users (id, email, password_hash, role, created_at, updated_at) FROM stdin;
e2d1870e-8d2a-49c7-9198-bca125470747	migration-admin@system.local		admin	2026-02-04 04:54:55.739822	2026-02-04 04:54:55.739822
eab9d641-c48d-4812-97e1-6859fec67118	admin@example.com	$argon2id$v=19$m=65536,t=3,p=4$rCrO0AHrijUEAZMA05k2MA$Zg4K2nnEJJLZWOaBPs/WGDtuWHQ/rTvp8/8rFTqQp+M	admin	2026-02-04 04:58:01.392046	2026-02-04 04:58:01.392046
045ce9f1-aa0c-4d01-b284-75b445c1c27a	demo@example.com	\N	guest	2026-02-04 04:58:01.80305	2026-02-04 04:58:01.80305
ff378c7b-e785-4994-8be3-a5586228f1d5	ejsadiarin@gmail.com	$argon2id$v=19$m=65536,t=3,p=4$DiXUvCkYJuSeNltoLTLZEQ$RcvZKWGUdzwkNaUk7NYmAa05g1IRJtJSDqUgOGTS1p4	admin	2026-02-04 05:00:25.571109	2026-02-04 05:00:25.571109
\.


--
-- Name: goose_db_version_id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public.goose_db_version_id_seq', 12, true);


--
-- Name: budget_categories budget_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.budget_categories
    ADD CONSTRAINT budget_categories_pkey PRIMARY KEY (id);


--
-- Name: budget_expense_tags budget_expense_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.budget_expense_tags
    ADD CONSTRAINT budget_expense_tags_pkey PRIMARY KEY (expense_id, tag_id);


--
-- Name: budget_expenses budget_expenses_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.budget_expenses
    ADD CONSTRAINT budget_expenses_pkey PRIMARY KEY (id);


--
-- Name: budget_incomes budget_incomes_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.budget_incomes
    ADD CONSTRAINT budget_incomes_pkey PRIMARY KEY (id);


--
-- Name: budget_tags budget_tags_name_user_unique; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.budget_tags
    ADD CONSTRAINT budget_tags_name_user_unique UNIQUE (name, user_id);


--
-- Name: budget_tags budget_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.budget_tags
    ADD CONSTRAINT budget_tags_pkey PRIMARY KEY (id);


--
-- Name: category_budgets category_budgets_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.category_budgets
    ADD CONSTRAINT category_budgets_pkey PRIMARY KEY (id);


--
-- Name: category_budgets category_budgets_user_id_category_id_month_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.category_budgets
    ADD CONSTRAINT category_budgets_user_id_category_id_month_key UNIQUE (user_id, category_id, month);


--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: savings_goals savings_goals_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.savings_goals
    ADD CONSTRAINT savings_goals_pkey PRIMARY KEY (id);


--
-- Name: service_health_history service_health_history_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.service_health_history
    ADD CONSTRAINT service_health_history_pkey PRIMARY KEY (id);


--
-- Name: services services_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT services_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_token_hash_key UNIQUE (token_hash);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_budget_categories_type; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_budget_categories_type ON public.budget_categories USING btree (category_type) WHERE (category_type IS NOT NULL);


--
-- Name: idx_budget_categories_user; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_budget_categories_user ON public.budget_categories USING btree (user_id);


--
-- Name: idx_budget_expenses_user; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_budget_expenses_user ON public.budget_expenses USING btree (user_id);


--
-- Name: idx_budget_tags_user; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_budget_tags_user ON public.budget_tags USING btree (user_id);


--
-- Name: idx_category_budgets_category; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_category_budgets_category ON public.category_budgets USING btree (category_id);


--
-- Name: idx_category_budgets_user_month; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_category_budgets_user_month ON public.category_budgets USING btree (user_id, month);


--
-- Name: idx_expense_tags_expense; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_expense_tags_expense ON public.budget_expense_tags USING btree (expense_id);


--
-- Name: idx_expense_tags_tag; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_expense_tags_tag ON public.budget_expense_tags USING btree (tag_id);


--
-- Name: idx_expenses_category; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_expenses_category ON public.budget_expenses USING btree (category_id);


--
-- Name: idx_expenses_date; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_expenses_date ON public.budget_expenses USING btree (expense_date DESC);


--
-- Name: idx_expenses_pagination; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_expenses_pagination ON public.budget_expenses USING btree (user_id, expense_date DESC, id);


--
-- Name: idx_incomes_pagination; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_incomes_pagination ON public.budget_incomes USING btree (user_id, created_at DESC);


--
-- Name: idx_incomes_recurring; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_incomes_recurring ON public.budget_incomes USING btree (user_id) WHERE (recurring_type IS NOT NULL);


--
-- Name: idx_incomes_user_date; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_incomes_user_date ON public.budget_incomes USING btree (user_id, date DESC);


--
-- Name: idx_savings_goals_deadline; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_savings_goals_deadline ON public.savings_goals USING btree (deadline) WHERE (deadline IS NOT NULL);


--
-- Name: idx_savings_goals_user; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_savings_goals_user ON public.savings_goals USING btree (user_id);


--
-- Name: idx_service_health_checked_at; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_service_health_checked_at ON public.service_health_history USING btree (checked_at DESC);


--
-- Name: idx_service_health_service_id; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_service_health_service_id ON public.service_health_history USING btree (service_id);


--
-- Name: idx_services_is_active; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_services_is_active ON public.services USING btree (is_active);


--
-- Name: idx_sessions_expires; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_sessions_expires ON public.sessions USING btree (expires_at);


--
-- Name: idx_sessions_token; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_sessions_token ON public.sessions USING btree (token_hash);


--
-- Name: idx_sessions_user; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_sessions_user ON public.sessions USING btree (user_id);


--
-- Name: idx_users_email; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_users_email ON public.users USING btree (email);


--
-- Name: idx_users_role; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX idx_users_role ON public.users USING btree (role);


--
-- Name: budget_categories budget_categories_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.budget_categories
    ADD CONSTRAINT budget_categories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: budget_expense_tags budget_expense_tags_expense_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.budget_expense_tags
    ADD CONSTRAINT budget_expense_tags_expense_id_fkey FOREIGN KEY (expense_id) REFERENCES public.budget_expenses(id) ON DELETE CASCADE;


--
-- Name: budget_expense_tags budget_expense_tags_tag_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.budget_expense_tags
    ADD CONSTRAINT budget_expense_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.budget_tags(id) ON DELETE CASCADE;


--
-- Name: budget_expenses budget_expenses_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.budget_expenses
    ADD CONSTRAINT budget_expenses_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.budget_categories(id);


--
-- Name: budget_expenses budget_expenses_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.budget_expenses
    ADD CONSTRAINT budget_expenses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: budget_incomes budget_incomes_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.budget_incomes
    ADD CONSTRAINT budget_incomes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: budget_tags budget_tags_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.budget_tags
    ADD CONSTRAINT budget_tags_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: category_budgets category_budgets_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.category_budgets
    ADD CONSTRAINT category_budgets_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.budget_categories(id) ON DELETE CASCADE;


--
-- Name: category_budgets category_budgets_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.category_budgets
    ADD CONSTRAINT category_budgets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: savings_goals savings_goals_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.savings_goals
    ADD CONSTRAINT savings_goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: service_health_history service_health_history_service_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.service_health_history
    ADD CONSTRAINT service_health_history_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id) ON DELETE CASCADE;


--
-- Name: sessions sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: cloud_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO neon_superuser WITH GRANT OPTION;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: cloud_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON TABLES TO neon_superuser WITH GRANT OPTION;


--
-- PostgreSQL database dump complete
--

\unrestrict QHMMZxAfphBX9eEM0CF9QekXEuhmnlflORMxkwX1baMagUAgtlBMyualf1JCWE9

