---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - httproute.yaml
  - deployment.yaml
  - service.yaml
  # - ../../common/cilium-network-policies

namespace: glance

labels:
  - pairs:
      app.kubernetes.io/name: glance
      app.kubernetes.io/part-of: web-apps
      app.kubernetes.io/managed-by: argocd

configMapGenerator:
  - name: glance-config
    files:
      - glance.yml
