#!/bin/bash

# all will have rw access
# sudo mount -t exfat -o umask=000 /dev/sda1 /mnt/sda1

# only user will have rw access
sudo mount -o rw,uid=$(id -u),gid=$(id -g) /dev/sda1 /mnt/sda
sudo mount -o rw,uid=$(id -u),gid=$(id -g) /dev/sdb1 /mnt/sdb
sudo mount -o rw,uid=$(id -u),gid=$(id -g) /dev/sdc1 /mnt/sdc
sudo mount -o rw,uid=$(id -u),gid=$(id -g) /dev/sdd1 /mnt/sdd
