// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budget.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addExpenseTag = `-- name: AddExpenseTag :exec

INSERT INTO budget_expense_tags (expense_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddExpenseTagParams struct {
	ExpenseID uuid.UUID `json:"expense_id"`
	TagID     uuid.UUID `json:"tag_id"`
}

// Expense Tags
func (q *Queries) AddExpenseTag(ctx context.Context, arg AddExpenseTagParams) error {
	_, err := q.db.Exec(ctx, addExpenseTag, arg.ExpenseID, arg.TagID)
	return err
}

const countExpenses = `-- name: CountExpenses :one
SELECT COUNT(*) FROM budget_expenses e
WHERE
    e.user_id = $1
    AND ($2::uuid IS NULL OR e.category_id = $2)
    AND ($3::date IS NULL OR e.expense_date >= $3::date)
    AND ($4::date IS NULL OR e.expense_date <= $4::date)
    AND ($5::text IS NULL OR e.recurring_type = $5)
`

type CountExpensesParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	CategoryID    pgtype.UUID `json:"category_id"`
	StartDate     pgtype.Date `json:"start_date"`
	EndDate       pgtype.Date `json:"end_date"`
	RecurringType pgtype.Text `json:"recurring_type"`
}

func (q *Queries) CountExpenses(ctx context.Context, arg CountExpensesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpenses,
		arg.UserID,
		arg.CategoryID,
		arg.StartDate,
		arg.EndDate,
		arg.RecurringType,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchExpenses = `-- name: CountSearchExpenses :one
SELECT COUNT(*) FROM budget_expenses e
WHERE
    e.user_id = $1
    AND e.description ILIKE '%' || $2 || '%'
    AND ($3::uuid IS NULL OR e.category_id = $3)
    AND ($4::date IS NULL OR e.expense_date >= $4::date)
    AND ($5::date IS NULL OR e.expense_date <= $5::date)
`

type CountSearchExpensesParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	Column2    pgtype.Text `json:"column_2"`
	CategoryID pgtype.UUID `json:"category_id"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

func (q *Queries) CountSearchExpenses(ctx context.Context, arg CountSearchExpensesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchExpenses,
		arg.UserID,
		arg.Column2,
		arg.CategoryID,
		arg.StartDate,
		arg.EndDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one

INSERT INTO budget_categories (
    name, color, icon, user_id
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, name, color, icon, created_at, user_id
`

type CreateCategoryParams struct {
	Name   string      `json:"name"`
	Color  pgtype.Text `json:"color"`
	Icon   pgtype.Text `json:"icon"`
	UserID uuid.UUID   `json:"user_id"`
}

// Categories
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (BudgetCategory, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Color,
		arg.Icon,
		arg.UserID,
	)
	var i BudgetCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const createCategoryBudget = `-- name: CreateCategoryBudget :one

INSERT INTO category_budgets (
    user_id, category_id, month, budget_amount
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, category_id, month, budget_amount, created_at, updated_at
`

type CreateCategoryBudgetParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	CategoryID   uuid.UUID      `json:"category_id"`
	Month        pgtype.Date    `json:"month"`
	BudgetAmount pgtype.Numeric `json:"budget_amount"`
}

// Category Budgets
func (q *Queries) CreateCategoryBudget(ctx context.Context, arg CreateCategoryBudgetParams) (CategoryBudget, error) {
	row := q.db.QueryRow(ctx, createCategoryBudget,
		arg.UserID,
		arg.CategoryID,
		arg.Month,
		arg.BudgetAmount,
	)
	var i CategoryBudget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Month,
		&i.BudgetAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExpense = `-- name: CreateExpense :one

INSERT INTO budget_expenses (
    description, amount, currency, category_id, expense_date, notes, user_id, recurring_type, start_date, end_date, priority_group_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, description, amount, currency, category_id, expense_date, created_at, updated_at, notes, user_id, recurring_type, start_date, end_date, priority_group_id
`

type CreateExpenseParams struct {
	Description     string         `json:"description"`
	Amount          pgtype.Numeric `json:"amount"`
	Currency        pgtype.Text    `json:"currency"`
	CategoryID      pgtype.UUID    `json:"category_id"`
	ExpenseDate     pgtype.Date    `json:"expense_date"`
	Notes           pgtype.Text    `json:"notes"`
	UserID          uuid.UUID      `json:"user_id"`
	RecurringType   pgtype.Text    `json:"recurring_type"`
	StartDate       pgtype.Date    `json:"start_date"`
	EndDate         pgtype.Date    `json:"end_date"`
	PriorityGroupID pgtype.UUID    `json:"priority_group_id"`
}

// Expenses
func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (BudgetExpense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.CategoryID,
		arg.ExpenseDate,
		arg.Notes,
		arg.UserID,
		arg.RecurringType,
		arg.StartDate,
		arg.EndDate,
		arg.PriorityGroupID,
	)
	var i BudgetExpense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.CategoryID,
		&i.ExpenseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
		&i.UserID,
		&i.RecurringType,
		&i.StartDate,
		&i.EndDate,
		&i.PriorityGroupID,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one

INSERT INTO budget_tags (
    name, color, user_id
) VALUES (
    $1, $2, $3
)
RETURNING id, name, color, created_at, user_id
`

type CreateTagParams struct {
	Name   string      `json:"name"`
	Color  pgtype.Text `json:"color"`
	UserID uuid.UUID   `json:"user_id"`
}

// Tags
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (BudgetTag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Name, arg.Color, arg.UserID)
	var i BudgetTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM budget_categories
WHERE id = $1 AND user_id = $2
`

type DeleteCategoryParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.UserID)
	return err
}

const deleteCategoryBudget = `-- name: DeleteCategoryBudget :exec
DELETE FROM category_budgets
WHERE id = $1 AND user_id = $2
`

type DeleteCategoryBudgetParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteCategoryBudget(ctx context.Context, arg DeleteCategoryBudgetParams) error {
	_, err := q.db.Exec(ctx, deleteCategoryBudget, arg.ID, arg.UserID)
	return err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM budget_expenses
WHERE id = $1 AND user_id = $2
`

type DeleteExpenseParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteExpense(ctx context.Context, arg DeleteExpenseParams) error {
	_, err := q.db.Exec(ctx, deleteExpense, arg.ID, arg.UserID)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM budget_tags
WHERE id = $1 AND user_id = $2
`

type DeleteTagParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.UserID)
	return err
}

const getAllCategorySpending = `-- name: GetAllCategorySpending :many
SELECT
    c.id,
    c.name,
    c.color,
    COALESCE(SUM(e.amount), 0::numeric) as total_amount,
    COUNT(e.id) as transaction_count
FROM budget_expenses e
JOIN budget_categories c ON e.category_id = c.id
WHERE
    ($1::uuid IS NULL OR e.user_id = $1)
    AND ($2::date IS NULL OR e.expense_date >= $2::date)
    AND ($3::date IS NULL OR e.expense_date <= $3::date)
GROUP BY c.id, c.name, c.color
ORDER BY total_amount DESC
`

type GetAllCategorySpendingParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetAllCategorySpendingRow struct {
	ID               uuid.UUID   `json:"id"`
	Name             string      `json:"name"`
	Color            pgtype.Text `json:"color"`
	TotalAmount      interface{} `json:"total_amount"`
	TransactionCount int64       `json:"transaction_count"`
}

func (q *Queries) GetAllCategorySpending(ctx context.Context, arg GetAllCategorySpendingParams) ([]GetAllCategorySpendingRow, error) {
	rows, err := q.db.Query(ctx, getAllCategorySpending, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllCategorySpendingRow{}
	for rows.Next() {
		var i GetAllCategorySpendingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.TotalAmount,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTotalSpending = `-- name: GetAllTotalSpending :one
SELECT
    COALESCE(SUM(amount), 0::numeric) as total_amount,
    COUNT(id) as transaction_count
FROM budget_expenses
WHERE
    ($1::uuid IS NULL OR user_id = $1)
    AND ($2::date IS NULL OR expense_date >= $2::date)
    AND ($3::date IS NULL OR expense_date <= $3::date)
`

type GetAllTotalSpendingParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetAllTotalSpendingRow struct {
	TotalAmount      interface{} `json:"total_amount"`
	TransactionCount int64       `json:"transaction_count"`
}

func (q *Queries) GetAllTotalSpending(ctx context.Context, arg GetAllTotalSpendingParams) (GetAllTotalSpendingRow, error) {
	row := q.db.QueryRow(ctx, getAllTotalSpending, arg.UserID, arg.StartDate, arg.EndDate)
	var i GetAllTotalSpendingRow
	err := row.Scan(&i.TotalAmount, &i.TransactionCount)
	return i, err
}

const getBudgetVariance = `-- name: GetBudgetVariance :many
SELECT 
    c.id as category_id,
    c.name as category_name,
    c.color as category_color,
    COALESCE(cb.budget_amount, 0::numeric) as budget_amount,
    COALESCE(SUM(e.amount), 0::numeric) as spent_amount,
    COUNT(e.id) as transaction_count
FROM budget_categories c
LEFT JOIN category_budgets cb ON c.id = cb.category_id 
    AND cb.user_id = c.user_id
    AND cb.month = $2::date
LEFT JOIN budget_expenses e ON c.id = e.category_id 
    AND e.user_id = c.user_id
    AND ($3::date IS NULL OR e.expense_date >= $3::date)
    AND ($4::date IS NULL OR e.expense_date <= $4::date)
WHERE c.user_id = $1
GROUP BY c.id, c.name, c.color, cb.budget_amount
ORDER BY c.name
`

type GetBudgetVarianceParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	Month     pgtype.Date `json:"month"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetBudgetVarianceRow struct {
	CategoryID       uuid.UUID      `json:"category_id"`
	CategoryName     string         `json:"category_name"`
	CategoryColor    pgtype.Text    `json:"category_color"`
	BudgetAmount     pgtype.Numeric `json:"budget_amount"`
	SpentAmount      interface{}    `json:"spent_amount"`
	TransactionCount int64          `json:"transaction_count"`
}

func (q *Queries) GetBudgetVariance(ctx context.Context, arg GetBudgetVarianceParams) ([]GetBudgetVarianceRow, error) {
	rows, err := q.db.Query(ctx, getBudgetVariance,
		arg.UserID,
		arg.Month,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBudgetVarianceRow{}
	for rows.Next() {
		var i GetBudgetVarianceRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryColor,
			&i.BudgetAmount,
			&i.SpentAmount,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, name, color, icon, created_at, user_id FROM budget_categories
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetCategoryParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (BudgetCategory, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.UserID)
	var i BudgetCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getCategoryBudget = `-- name: GetCategoryBudget :one
SELECT id, user_id, category_id, month, budget_amount, created_at, updated_at FROM category_budgets
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetCategoryBudgetParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetCategoryBudget(ctx context.Context, arg GetCategoryBudgetParams) (CategoryBudget, error) {
	row := q.db.QueryRow(ctx, getCategoryBudget, arg.ID, arg.UserID)
	var i CategoryBudget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Month,
		&i.BudgetAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBudgetByCategoryAndMonth = `-- name: GetCategoryBudgetByCategoryAndMonth :one
SELECT id, user_id, category_id, month, budget_amount, created_at, updated_at FROM category_budgets
WHERE user_id = $1 AND category_id = $2 AND month = $3 LIMIT 1
`

type GetCategoryBudgetByCategoryAndMonthParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	CategoryID uuid.UUID   `json:"category_id"`
	Month      pgtype.Date `json:"month"`
}

func (q *Queries) GetCategoryBudgetByCategoryAndMonth(ctx context.Context, arg GetCategoryBudgetByCategoryAndMonthParams) (CategoryBudget, error) {
	row := q.db.QueryRow(ctx, getCategoryBudgetByCategoryAndMonth, arg.UserID, arg.CategoryID, arg.Month)
	var i CategoryBudget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Month,
		&i.BudgetAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, color, icon, created_at, user_id FROM budget_categories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (BudgetCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i BudgetCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getCategorySpending = `-- name: GetCategorySpending :many
SELECT
    c.id,
    c.name,
    c.color,
    COALESCE(SUM(e.amount), 0::numeric) as total_amount,
    COUNT(e.id) as transaction_count
FROM budget_expenses e
JOIN budget_categories c ON e.category_id = c.id
WHERE
    e.user_id = $1
    AND ($2::date IS NULL OR e.expense_date >= $2::date)
    AND ($3::date IS NULL OR e.expense_date <= $3::date)
GROUP BY c.id, c.name, c.color
ORDER BY total_amount DESC
`

type GetCategorySpendingParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetCategorySpendingRow struct {
	ID               uuid.UUID   `json:"id"`
	Name             string      `json:"name"`
	Color            pgtype.Text `json:"color"`
	TotalAmount      interface{} `json:"total_amount"`
	TransactionCount int64       `json:"transaction_count"`
}

func (q *Queries) GetCategorySpending(ctx context.Context, arg GetCategorySpendingParams) ([]GetCategorySpendingRow, error) {
	rows, err := q.db.Query(ctx, getCategorySpending, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategorySpendingRow{}
	for rows.Next() {
		var i GetCategorySpendingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.TotalAmount,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailySpending = `-- name: GetDailySpending :many
SELECT
    expense_date,
    COALESCE(SUM(amount), 0::numeric) as total_amount,
    COUNT(id) as transaction_count
FROM budget_expenses
WHERE
    user_id = $1
    AND ($2::date IS NULL OR expense_date >= $2::date)
    AND ($3::date IS NULL OR expense_date <= $3::date)
GROUP BY expense_date
ORDER BY expense_date ASC
`

type GetDailySpendingParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetDailySpendingRow struct {
	ExpenseDate      pgtype.Date `json:"expense_date"`
	TotalAmount      interface{} `json:"total_amount"`
	TransactionCount int64       `json:"transaction_count"`
}

func (q *Queries) GetDailySpending(ctx context.Context, arg GetDailySpendingParams) ([]GetDailySpendingRow, error) {
	rows, err := q.db.Query(ctx, getDailySpending, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailySpendingRow{}
	for rows.Next() {
		var i GetDailySpendingRow
		if err := rows.Scan(&i.ExpenseDate, &i.TotalAmount, &i.TransactionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailySpendingForVelocity = `-- name: GetDailySpendingForVelocity :many

SELECT 
    expense_date,
    COALESCE(SUM(amount), 0::numeric) as total_amount,
    COUNT(id) as transaction_count
FROM budget_expenses
WHERE user_id = $1
    AND expense_date >= $2
    AND expense_date <= $3
GROUP BY expense_date
ORDER BY expense_date ASC
`

type GetDailySpendingForVelocityParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	ExpenseDate   pgtype.Date `json:"expense_date"`
	ExpenseDate_2 pgtype.Date `json:"expense_date_2"`
}

type GetDailySpendingForVelocityRow struct {
	ExpenseDate      pgtype.Date `json:"expense_date"`
	TotalAmount      interface{} `json:"total_amount"`
	TransactionCount int64       `json:"transaction_count"`
}

// Spending Velocity & Trends
func (q *Queries) GetDailySpendingForVelocity(ctx context.Context, arg GetDailySpendingForVelocityParams) ([]GetDailySpendingForVelocityRow, error) {
	rows, err := q.db.Query(ctx, getDailySpendingForVelocity, arg.UserID, arg.ExpenseDate, arg.ExpenseDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailySpendingForVelocityRow{}
	for rows.Next() {
		var i GetDailySpendingForVelocityRow
		if err := rows.Scan(&i.ExpenseDate, &i.TotalAmount, &i.TransactionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpense = `-- name: GetExpense :one
SELECT id, description, amount, currency, category_id, expense_date, created_at, updated_at, notes, user_id, recurring_type, start_date, end_date, priority_group_id FROM budget_expenses
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetExpenseParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetExpense(ctx context.Context, arg GetExpenseParams) (BudgetExpense, error) {
	row := q.db.QueryRow(ctx, getExpense, arg.ID, arg.UserID)
	var i BudgetExpense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.CategoryID,
		&i.ExpenseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
		&i.UserID,
		&i.RecurringType,
		&i.StartDate,
		&i.EndDate,
		&i.PriorityGroupID,
	)
	return i, err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, description, amount, currency, category_id, expense_date, created_at, updated_at, notes, user_id, recurring_type, start_date, end_date, priority_group_id FROM budget_expenses
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetExpenseByID(ctx context.Context, id uuid.UUID) (BudgetExpense, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, id)
	var i BudgetExpense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.CategoryID,
		&i.ExpenseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
		&i.UserID,
		&i.RecurringType,
		&i.StartDate,
		&i.EndDate,
		&i.PriorityGroupID,
	)
	return i, err
}

const getExpenseTags = `-- name: GetExpenseTags :many
SELECT t.id, t.name, t.color, t.created_at, t.user_id
FROM budget_tags t
JOIN budget_expense_tags et ON t.id = et.tag_id
WHERE et.expense_id = $1
`

func (q *Queries) GetExpenseTags(ctx context.Context, expenseID uuid.UUID) ([]BudgetTag, error) {
	rows, err := q.db.Query(ctx, getExpenseTags, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetTag{}
	for rows.Next() {
		var i BudgetTag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpensesByDateRange = `-- name: GetExpensesByDateRange :many

SELECT id, description, amount, currency, category_id, expense_date, created_at, updated_at, notes, user_id, recurring_type, start_date, end_date, priority_group_id FROM budget_expenses
WHERE user_id = $1 AND expense_date BETWEEN $2 AND $3
ORDER BY expense_date DESC
`

type GetExpensesByDateRangeParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	ExpenseDate   pgtype.Date `json:"expense_date"`
	ExpenseDate_2 pgtype.Date `json:"expense_date_2"`
}

// Statistics (filtered by user)
func (q *Queries) GetExpensesByDateRange(ctx context.Context, arg GetExpensesByDateRangeParams) ([]BudgetExpense, error) {
	rows, err := q.db.Query(ctx, getExpensesByDateRange, arg.UserID, arg.ExpenseDate, arg.ExpenseDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetExpense{}
	for rows.Next() {
		var i BudgetExpense
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.ExpenseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Notes,
			&i.UserID,
			&i.RecurringType,
			&i.StartDate,
			&i.EndDate,
			&i.PriorityGroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMerchantSpendingTrend = `-- name: GetMerchantSpendingTrend :many
SELECT 
    description,
    TO_CHAR(expense_date, 'YYYY-MM') as month,
    COALESCE(SUM(amount), 0::numeric) as total_amount,
    COUNT(id) as transaction_count
FROM budget_expenses
WHERE user_id = $1
    AND description ILIKE '%' || $2 || '%'
GROUP BY description, month
ORDER BY month DESC
`

type GetMerchantSpendingTrendParams struct {
	UserID          uuid.UUID   `json:"user_id"`
	MerchantPattern pgtype.Text `json:"merchant_pattern"`
}

type GetMerchantSpendingTrendRow struct {
	Description      string      `json:"description"`
	Month            string      `json:"month"`
	TotalAmount      interface{} `json:"total_amount"`
	TransactionCount int64       `json:"transaction_count"`
}

func (q *Queries) GetMerchantSpendingTrend(ctx context.Context, arg GetMerchantSpendingTrendParams) ([]GetMerchantSpendingTrendRow, error) {
	rows, err := q.db.Query(ctx, getMerchantSpendingTrend, arg.UserID, arg.MerchantPattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMerchantSpendingTrendRow{}
	for rows.Next() {
		var i GetMerchantSpendingTrendRow
		if err := rows.Scan(
			&i.Description,
			&i.Month,
			&i.TotalAmount,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthToDateSpending = `-- name: GetMonthToDateSpending :one
SELECT 
    COALESCE(SUM(amount), 0::numeric) as total_amount,
    COUNT(id) as transaction_count
FROM budget_expenses
WHERE user_id = $1
    AND expense_date >= $2
    AND expense_date <= $3
`

type GetMonthToDateSpendingParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	ExpenseDate   pgtype.Date `json:"expense_date"`
	ExpenseDate_2 pgtype.Date `json:"expense_date_2"`
}

type GetMonthToDateSpendingRow struct {
	TotalAmount      interface{} `json:"total_amount"`
	TransactionCount int64       `json:"transaction_count"`
}

func (q *Queries) GetMonthToDateSpending(ctx context.Context, arg GetMonthToDateSpendingParams) (GetMonthToDateSpendingRow, error) {
	row := q.db.QueryRow(ctx, getMonthToDateSpending, arg.UserID, arg.ExpenseDate, arg.ExpenseDate_2)
	var i GetMonthToDateSpendingRow
	err := row.Scan(&i.TotalAmount, &i.TransactionCount)
	return i, err
}

const getMonthlySpending = `-- name: GetMonthlySpending :many
SELECT
    TO_CHAR(expense_date, 'YYYY-MM') as month,
    COALESCE(SUM(amount), 0::numeric) as total_amount,
    COUNT(id) as transaction_count
FROM budget_expenses
WHERE user_id = $1
GROUP BY month
ORDER BY month DESC
LIMIT 12
`

type GetMonthlySpendingRow struct {
	Month            string      `json:"month"`
	TotalAmount      interface{} `json:"total_amount"`
	TransactionCount int64       `json:"transaction_count"`
}

func (q *Queries) GetMonthlySpending(ctx context.Context, userID uuid.UUID) ([]GetMonthlySpendingRow, error) {
	rows, err := q.db.Query(ctx, getMonthlySpending, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlySpendingRow{}
	for rows.Next() {
		var i GetMonthlySpendingRow
		if err := rows.Scan(&i.Month, &i.TotalAmount, &i.TransactionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPriorityGroupBySlug = `-- name: GetPriorityGroupBySlug :one
SELECT id, name, slug, display_order, created_at FROM budget_priority_groups
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetPriorityGroupBySlug(ctx context.Context, slug string) (BudgetPriorityGroup, error) {
	row := q.db.QueryRow(ctx, getPriorityGroupBySlug, slug)
	var i BudgetPriorityGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getSpendingByDayOfWeek = `-- name: GetSpendingByDayOfWeek :many

SELECT 
    EXTRACT(DOW FROM expense_date) as day_of_week,
    COALESCE(SUM(amount), 0::numeric) as total_amount,
    COUNT(id) as transaction_count,
    AVG(amount) as avg_amount
FROM budget_expenses
WHERE user_id = $1
    AND ($2::date IS NULL OR expense_date >= $2::date)
    AND ($3::date IS NULL OR expense_date <= $3::date)
GROUP BY day_of_week
ORDER BY day_of_week
`

type GetSpendingByDayOfWeekParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetSpendingByDayOfWeekRow struct {
	DayOfWeek        pgtype.Numeric `json:"day_of_week"`
	TotalAmount      interface{}    `json:"total_amount"`
	TransactionCount int64          `json:"transaction_count"`
	AvgAmount        float64        `json:"avg_amount"`
}

// Weekday Analysis
func (q *Queries) GetSpendingByDayOfWeek(ctx context.Context, arg GetSpendingByDayOfWeekParams) ([]GetSpendingByDayOfWeekRow, error) {
	rows, err := q.db.Query(ctx, getSpendingByDayOfWeek, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSpendingByDayOfWeekRow{}
	for rows.Next() {
		var i GetSpendingByDayOfWeekRow
		if err := rows.Scan(
			&i.DayOfWeek,
			&i.TotalAmount,
			&i.TransactionCount,
			&i.AvgAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpendingByPriorityGroup = `-- name: GetSpendingByPriorityGroup :many

SELECT 
    pg.id as priority_group_id,
    pg.name as priority_group_name,
    pg.slug as priority_group_slug,
    pg.display_order,
    COALESCE(SUM(e.amount), 0::numeric) as total_amount,
    COUNT(e.id) as transaction_count
FROM budget_priority_groups pg
LEFT JOIN budget_expenses e ON e.priority_group_id = pg.id
    AND e.user_id = $1
    AND ($2::date IS NULL OR e.expense_date >= $2::date)
    AND ($3::date IS NULL OR e.expense_date <= $3::date)
GROUP BY pg.id, pg.name, pg.slug, pg.display_order
ORDER BY pg.display_order
`

type GetSpendingByPriorityGroupParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetSpendingByPriorityGroupRow struct {
	PriorityGroupID   uuid.UUID   `json:"priority_group_id"`
	PriorityGroupName string      `json:"priority_group_name"`
	PriorityGroupSlug string      `json:"priority_group_slug"`
	DisplayOrder      int32       `json:"display_order"`
	TotalAmount       interface{} `json:"total_amount"`
	TransactionCount  int64       `json:"transaction_count"`
}

// 50/30/20 Analysis
func (q *Queries) GetSpendingByPriorityGroup(ctx context.Context, arg GetSpendingByPriorityGroupParams) ([]GetSpendingByPriorityGroupRow, error) {
	rows, err := q.db.Query(ctx, getSpendingByPriorityGroup, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSpendingByPriorityGroupRow{}
	for rows.Next() {
		var i GetSpendingByPriorityGroupRow
		if err := rows.Scan(
			&i.PriorityGroupID,
			&i.PriorityGroupName,
			&i.PriorityGroupSlug,
			&i.DisplayOrder,
			&i.TotalAmount,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTag = `-- name: GetTag :one
SELECT id, name, color, created_at, user_id FROM budget_tags
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetTagParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTag(ctx context.Context, arg GetTagParams) (BudgetTag, error) {
	row := q.db.QueryRow(ctx, getTag, arg.ID, arg.UserID)
	var i BudgetTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, color, created_at, user_id FROM budget_tags
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTagByID(ctx context.Context, id uuid.UUID) (BudgetTag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i BudgetTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const getTopMerchants = `-- name: GetTopMerchants :many

SELECT 
    description,
    COALESCE(SUM(amount), 0::numeric) as total_amount,
    COUNT(id) as transaction_count,
    AVG(amount) as avg_amount
FROM budget_expenses
WHERE user_id = $1
    AND ($2::date IS NULL OR expense_date >= $2::date)
    AND ($3::date IS NULL OR expense_date <= $3::date)
GROUP BY description
ORDER BY total_amount DESC
LIMIT $4
`

type GetTopMerchantsParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Limit     pgtype.Int4 `json:"limit"`
}

type GetTopMerchantsRow struct {
	Description      string      `json:"description"`
	TotalAmount      interface{} `json:"total_amount"`
	TransactionCount int64       `json:"transaction_count"`
	AvgAmount        float64     `json:"avg_amount"`
}

// Merchant Analysis
func (q *Queries) GetTopMerchants(ctx context.Context, arg GetTopMerchantsParams) ([]GetTopMerchantsRow, error) {
	rows, err := q.db.Query(ctx, getTopMerchants,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopMerchantsRow{}
	for rows.Next() {
		var i GetTopMerchantsRow
		if err := rows.Scan(
			&i.Description,
			&i.TotalAmount,
			&i.TransactionCount,
			&i.AvgAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalSpending = `-- name: GetTotalSpending :one
SELECT
    COALESCE(SUM(amount), 0::numeric) as total_amount,
    COUNT(id) as transaction_count
FROM budget_expenses
WHERE
    user_id = $1
    AND ($2::date IS NULL OR expense_date >= $2::date)
    AND ($3::date IS NULL OR expense_date <= $3::date)
`

type GetTotalSpendingParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetTotalSpendingRow struct {
	TotalAmount      interface{} `json:"total_amount"`
	TransactionCount int64       `json:"transaction_count"`
}

func (q *Queries) GetTotalSpending(ctx context.Context, arg GetTotalSpendingParams) (GetTotalSpendingRow, error) {
	row := q.db.QueryRow(ctx, getTotalSpending, arg.UserID, arg.StartDate, arg.EndDate)
	var i GetTotalSpendingRow
	err := row.Scan(&i.TotalAmount, &i.TransactionCount)
	return i, err
}

const getUnclassifiedExpenseCount = `-- name: GetUnclassifiedExpenseCount :one
SELECT 
    COUNT(id) as unclassified_count,
    COALESCE(SUM(amount), 0::numeric) as unclassified_amount
FROM budget_expenses
WHERE user_id = $1
    AND priority_group_id IS NULL
    AND ($2::date IS NULL OR expense_date >= $2::date)
    AND ($3::date IS NULL OR expense_date <= $3::date)
`

type GetUnclassifiedExpenseCountParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetUnclassifiedExpenseCountRow struct {
	UnclassifiedCount  int64       `json:"unclassified_count"`
	UnclassifiedAmount interface{} `json:"unclassified_amount"`
}

func (q *Queries) GetUnclassifiedExpenseCount(ctx context.Context, arg GetUnclassifiedExpenseCountParams) (GetUnclassifiedExpenseCountRow, error) {
	row := q.db.QueryRow(ctx, getUnclassifiedExpenseCount, arg.UserID, arg.StartDate, arg.EndDate)
	var i GetUnclassifiedExpenseCountRow
	err := row.Scan(&i.UnclassifiedCount, &i.UnclassifiedAmount)
	return i, err
}

const getUpcomingRecurringExpenses = `-- name: GetUpcomingRecurringExpenses :many

SELECT 
    id,
    description,
    amount,
    currency,
    recurring_type,
    start_date,
    end_date,
    category_id
FROM budget_expenses
WHERE user_id = $1
    AND recurring_type IS NOT NULL
    AND start_date <= $2
    AND (end_date IS NULL OR end_date >= CURRENT_DATE)
ORDER BY 
    CASE recurring_type
        WHEN 'daily' THEN 1
        WHEN 'weekly' THEN 2
        WHEN 'monthly' THEN 3
        WHEN 'yearly' THEN 4
    END,
    description
`

type GetUpcomingRecurringExpensesParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	StartDate pgtype.Date `json:"start_date"`
}

type GetUpcomingRecurringExpensesRow struct {
	ID            uuid.UUID      `json:"id"`
	Description   string         `json:"description"`
	Amount        pgtype.Numeric `json:"amount"`
	Currency      pgtype.Text    `json:"currency"`
	RecurringType pgtype.Text    `json:"recurring_type"`
	StartDate     pgtype.Date    `json:"start_date"`
	EndDate       pgtype.Date    `json:"end_date"`
	CategoryID    pgtype.UUID    `json:"category_id"`
}

// Upcoming Recurring Expenses Forecasting
func (q *Queries) GetUpcomingRecurringExpenses(ctx context.Context, arg GetUpcomingRecurringExpensesParams) ([]GetUpcomingRecurringExpensesRow, error) {
	rows, err := q.db.Query(ctx, getUpcomingRecurringExpenses, arg.UserID, arg.StartDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUpcomingRecurringExpensesRow{}
	for rows.Next() {
		var i GetUpcomingRecurringExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.RecurringType,
			&i.StartDate,
			&i.EndDate,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT bc.id, bc.name, bc.color, bc.icon, bc.created_at, bc.user_id, u.email as user_email
FROM budget_categories bc
JOIN users u ON bc.user_id = u.id
ORDER BY bc.name
`

type ListAllCategoriesRow struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Color     pgtype.Text      `json:"color"`
	Icon      pgtype.Text      `json:"icon"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UserID    uuid.UUID        `json:"user_id"`
	UserEmail string           `json:"user_email"`
}

func (q *Queries) ListAllCategories(ctx context.Context) ([]ListAllCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllCategoriesRow{}
	for rows.Next() {
		var i ListAllCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Icon,
			&i.CreatedAt,
			&i.UserID,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllExpenses = `-- name: ListAllExpenses :many
SELECT e.id, e.description, e.amount, e.currency, e.category_id, e.expense_date, e.created_at, e.updated_at, e.notes, e.user_id, e.recurring_type, e.start_date, e.end_date, e.priority_group_id, c.name as category_name, c.color as category_color, c.icon as category_icon, u.email as user_email,
    pg.name as priority_group_name, pg.slug as priority_group_slug
FROM budget_expenses e
LEFT JOIN budget_categories c ON e.category_id = c.id
JOIN users u ON e.user_id = u.id
LEFT JOIN budget_priority_groups pg ON e.priority_group_id = pg.id
WHERE
    ($1::uuid IS NULL OR e.user_id = $1)
    AND ($2::uuid IS NULL OR e.category_id = $2)
    AND ($3::date IS NULL OR e.expense_date >= $3::date)
    AND ($4::date IS NULL OR e.expense_date <= $4::date)
ORDER BY e.expense_date DESC, e.created_at DESC
`

type ListAllExpensesParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

type ListAllExpensesRow struct {
	ID                uuid.UUID        `json:"id"`
	Description       string           `json:"description"`
	Amount            pgtype.Numeric   `json:"amount"`
	Currency          pgtype.Text      `json:"currency"`
	CategoryID        pgtype.UUID      `json:"category_id"`
	ExpenseDate       pgtype.Date      `json:"expense_date"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	Notes             pgtype.Text      `json:"notes"`
	UserID            uuid.UUID        `json:"user_id"`
	RecurringType     pgtype.Text      `json:"recurring_type"`
	StartDate         pgtype.Date      `json:"start_date"`
	EndDate           pgtype.Date      `json:"end_date"`
	PriorityGroupID   pgtype.UUID      `json:"priority_group_id"`
	CategoryName      pgtype.Text      `json:"category_name"`
	CategoryColor     pgtype.Text      `json:"category_color"`
	CategoryIcon      pgtype.Text      `json:"category_icon"`
	UserEmail         string           `json:"user_email"`
	PriorityGroupName pgtype.Text      `json:"priority_group_name"`
	PriorityGroupSlug pgtype.Text      `json:"priority_group_slug"`
}

func (q *Queries) ListAllExpenses(ctx context.Context, arg ListAllExpensesParams) ([]ListAllExpensesRow, error) {
	rows, err := q.db.Query(ctx, listAllExpenses,
		arg.UserID,
		arg.CategoryID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllExpensesRow{}
	for rows.Next() {
		var i ListAllExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.ExpenseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Notes,
			&i.UserID,
			&i.RecurringType,
			&i.StartDate,
			&i.EndDate,
			&i.PriorityGroupID,
			&i.CategoryName,
			&i.CategoryColor,
			&i.CategoryIcon,
			&i.UserEmail,
			&i.PriorityGroupName,
			&i.PriorityGroupSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTags = `-- name: ListAllTags :many
SELECT bt.id, bt.name, bt.color, bt.created_at, bt.user_id, u.email as user_email
FROM budget_tags bt
JOIN users u ON bt.user_id = u.id
ORDER BY bt.name
`

type ListAllTagsRow struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Color     pgtype.Text      `json:"color"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UserID    uuid.UUID        `json:"user_id"`
	UserEmail string           `json:"user_email"`
}

func (q *Queries) ListAllTags(ctx context.Context) ([]ListAllTagsRow, error) {
	rows, err := q.db.Query(ctx, listAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTagsRow{}
	for rows.Next() {
		var i ListAllTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UserID,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, color, icon, created_at, user_id FROM budget_categories
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context, userID uuid.UUID) ([]BudgetCategory, error) {
	rows, err := q.db.Query(ctx, listCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetCategory{}
	for rows.Next() {
		var i BudgetCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Icon,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryBudgets = `-- name: ListCategoryBudgets :many
SELECT cb.id, cb.user_id, cb.category_id, cb.month, cb.budget_amount, cb.created_at, cb.updated_at, c.name as category_name, c.color as category_color
FROM category_budgets cb
JOIN budget_categories c ON cb.category_id = c.id
WHERE cb.user_id = $1
    AND ($2::date IS NULL OR cb.month = $2::date)
ORDER BY cb.month DESC, c.name
`

type ListCategoryBudgetsParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Month  pgtype.Date `json:"month"`
}

type ListCategoryBudgetsRow struct {
	ID            uuid.UUID        `json:"id"`
	UserID        uuid.UUID        `json:"user_id"`
	CategoryID    uuid.UUID        `json:"category_id"`
	Month         pgtype.Date      `json:"month"`
	BudgetAmount  pgtype.Numeric   `json:"budget_amount"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	CategoryName  string           `json:"category_name"`
	CategoryColor pgtype.Text      `json:"category_color"`
}

func (q *Queries) ListCategoryBudgets(ctx context.Context, arg ListCategoryBudgetsParams) ([]ListCategoryBudgetsRow, error) {
	rows, err := q.db.Query(ctx, listCategoryBudgets, arg.UserID, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoryBudgetsRow{}
	for rows.Next() {
		var i ListCategoryBudgetsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Month,
			&i.BudgetAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenses = `-- name: ListExpenses :many
SELECT e.id, e.description, e.amount, e.currency, e.category_id, e.expense_date, e.created_at, e.updated_at, e.notes, e.user_id, e.recurring_type, e.start_date, e.end_date, e.priority_group_id, c.name as category_name, c.color as category_color, c.icon as category_icon,
    pg.name as priority_group_name, pg.slug as priority_group_slug
FROM budget_expenses e
LEFT JOIN budget_categories c ON e.category_id = c.id
LEFT JOIN budget_priority_groups pg ON e.priority_group_id = pg.id
WHERE
    e.user_id = $1
    AND ($4::uuid IS NULL OR e.category_id = $4)
    AND ($5::date IS NULL OR e.expense_date >= $5::date)
    AND ($6::date IS NULL OR e.expense_date <= $6::date)
    AND ($7::text IS NULL OR e.recurring_type = $7)
ORDER BY e.expense_date DESC, e.created_at DESC
LIMIT $2 OFFSET $3
`

type ListExpensesParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
	CategoryID    pgtype.UUID `json:"category_id"`
	StartDate     pgtype.Date `json:"start_date"`
	EndDate       pgtype.Date `json:"end_date"`
	RecurringType pgtype.Text `json:"recurring_type"`
}

type ListExpensesRow struct {
	ID                uuid.UUID        `json:"id"`
	Description       string           `json:"description"`
	Amount            pgtype.Numeric   `json:"amount"`
	Currency          pgtype.Text      `json:"currency"`
	CategoryID        pgtype.UUID      `json:"category_id"`
	ExpenseDate       pgtype.Date      `json:"expense_date"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	Notes             pgtype.Text      `json:"notes"`
	UserID            uuid.UUID        `json:"user_id"`
	RecurringType     pgtype.Text      `json:"recurring_type"`
	StartDate         pgtype.Date      `json:"start_date"`
	EndDate           pgtype.Date      `json:"end_date"`
	PriorityGroupID   pgtype.UUID      `json:"priority_group_id"`
	CategoryName      pgtype.Text      `json:"category_name"`
	CategoryColor     pgtype.Text      `json:"category_color"`
	CategoryIcon      pgtype.Text      `json:"category_icon"`
	PriorityGroupName pgtype.Text      `json:"priority_group_name"`
	PriorityGroupSlug pgtype.Text      `json:"priority_group_slug"`
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]ListExpensesRow, error) {
	rows, err := q.db.Query(ctx, listExpenses,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.StartDate,
		arg.EndDate,
		arg.RecurringType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpensesRow{}
	for rows.Next() {
		var i ListExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.ExpenseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Notes,
			&i.UserID,
			&i.RecurringType,
			&i.StartDate,
			&i.EndDate,
			&i.PriorityGroupID,
			&i.CategoryName,
			&i.CategoryColor,
			&i.CategoryIcon,
			&i.PriorityGroupName,
			&i.PriorityGroupSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriorityGroups = `-- name: ListPriorityGroups :many

SELECT id, name, slug, display_order, created_at FROM budget_priority_groups
ORDER BY display_order
`

// Priority Groups
func (q *Queries) ListPriorityGroups(ctx context.Context) ([]BudgetPriorityGroup, error) {
	rows, err := q.db.Query(ctx, listPriorityGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetPriorityGroup{}
	for rows.Next() {
		var i BudgetPriorityGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, color, created_at, user_id FROM budget_tags
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context, userID uuid.UUID) ([]BudgetTag, error) {
	rows, err := q.db.Query(ctx, listTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetTag{}
	for rows.Next() {
		var i BudgetTag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllExpenseTags = `-- name: RemoveAllExpenseTags :exec
DELETE FROM budget_expense_tags
WHERE expense_id = $1
`

func (q *Queries) RemoveAllExpenseTags(ctx context.Context, expenseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeAllExpenseTags, expenseID)
	return err
}

const removeExpenseTag = `-- name: RemoveExpenseTag :exec
DELETE FROM budget_expense_tags
WHERE expense_id = $1 AND tag_id = $2
`

type RemoveExpenseTagParams struct {
	ExpenseID uuid.UUID `json:"expense_id"`
	TagID     uuid.UUID `json:"tag_id"`
}

func (q *Queries) RemoveExpenseTag(ctx context.Context, arg RemoveExpenseTagParams) error {
	_, err := q.db.Exec(ctx, removeExpenseTag, arg.ExpenseID, arg.TagID)
	return err
}

const searchExpenses = `-- name: SearchExpenses :many
SELECT e.id, e.description, e.amount, e.currency, e.category_id, e.expense_date, e.created_at, e.updated_at, e.notes, e.user_id, e.recurring_type, e.start_date, e.end_date, e.priority_group_id, c.name as category_name, c.color as category_color, c.icon as category_icon,
    pg.name as priority_group_name, pg.slug as priority_group_slug
FROM budget_expenses e
LEFT JOIN budget_categories c ON e.category_id = c.id
LEFT JOIN budget_priority_groups pg ON e.priority_group_id = pg.id
WHERE
    e.user_id = $1
    AND e.description ILIKE '%' || $2 || '%'
    AND ($5::uuid IS NULL OR e.category_id = $5)
    AND ($6::date IS NULL OR e.expense_date >= $6::date)
    AND ($7::date IS NULL OR e.expense_date <= $7::date)
ORDER BY e.expense_date DESC, e.created_at DESC
LIMIT $3 OFFSET $4
`

type SearchExpensesParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	Column2    pgtype.Text `json:"column_2"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	CategoryID pgtype.UUID `json:"category_id"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

type SearchExpensesRow struct {
	ID                uuid.UUID        `json:"id"`
	Description       string           `json:"description"`
	Amount            pgtype.Numeric   `json:"amount"`
	Currency          pgtype.Text      `json:"currency"`
	CategoryID        pgtype.UUID      `json:"category_id"`
	ExpenseDate       pgtype.Date      `json:"expense_date"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	Notes             pgtype.Text      `json:"notes"`
	UserID            uuid.UUID        `json:"user_id"`
	RecurringType     pgtype.Text      `json:"recurring_type"`
	StartDate         pgtype.Date      `json:"start_date"`
	EndDate           pgtype.Date      `json:"end_date"`
	PriorityGroupID   pgtype.UUID      `json:"priority_group_id"`
	CategoryName      pgtype.Text      `json:"category_name"`
	CategoryColor     pgtype.Text      `json:"category_color"`
	CategoryIcon      pgtype.Text      `json:"category_icon"`
	PriorityGroupName pgtype.Text      `json:"priority_group_name"`
	PriorityGroupSlug pgtype.Text      `json:"priority_group_slug"`
}

func (q *Queries) SearchExpenses(ctx context.Context, arg SearchExpensesParams) ([]SearchExpensesRow, error) {
	rows, err := q.db.Query(ctx, searchExpenses,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchExpensesRow{}
	for rows.Next() {
		var i SearchExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.ExpenseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Notes,
			&i.UserID,
			&i.RecurringType,
			&i.StartDate,
			&i.EndDate,
			&i.PriorityGroupID,
			&i.CategoryName,
			&i.CategoryColor,
			&i.CategoryIcon,
			&i.PriorityGroupName,
			&i.PriorityGroupSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE budget_categories
SET
    name = COALESCE($3, name),
    color = COALESCE($4, color),
    icon = COALESCE($5, icon)
WHERE id = $1 AND user_id = $2
RETURNING id, name, color, icon, created_at, user_id
`

type UpdateCategoryParams struct {
	ID     uuid.UUID   `json:"id"`
	UserID uuid.UUID   `json:"user_id"`
	Name   pgtype.Text `json:"name"`
	Color  pgtype.Text `json:"color"`
	Icon   pgtype.Text `json:"icon"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (BudgetCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Color,
		arg.Icon,
	)
	var i BudgetCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Icon,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}

const updateCategoryBudget = `-- name: UpdateCategoryBudget :one
UPDATE category_budgets
SET
    budget_amount = COALESCE($3, budget_amount),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, category_id, month, budget_amount, created_at, updated_at
`

type UpdateCategoryBudgetParams struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	BudgetAmount pgtype.Numeric `json:"budget_amount"`
}

func (q *Queries) UpdateCategoryBudget(ctx context.Context, arg UpdateCategoryBudgetParams) (CategoryBudget, error) {
	row := q.db.QueryRow(ctx, updateCategoryBudget, arg.ID, arg.UserID, arg.BudgetAmount)
	var i CategoryBudget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Month,
		&i.BudgetAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE budget_expenses
SET
    description = COALESCE($3, description),
    amount = COALESCE($4, amount),
    currency = COALESCE($5, currency),
    category_id = COALESCE($6, category_id),
    expense_date = COALESCE($7, expense_date),
    notes = COALESCE($8, notes),
    recurring_type = COALESCE($9, recurring_type),
    start_date = COALESCE($10, start_date),
    end_date = COALESCE($11, end_date),
    priority_group_id = COALESCE($12, priority_group_id),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, description, amount, currency, category_id, expense_date, created_at, updated_at, notes, user_id, recurring_type, start_date, end_date, priority_group_id
`

type UpdateExpenseParams struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	Description     pgtype.Text    `json:"description"`
	Amount          pgtype.Numeric `json:"amount"`
	Currency        pgtype.Text    `json:"currency"`
	CategoryID      pgtype.UUID    `json:"category_id"`
	ExpenseDate     pgtype.Date    `json:"expense_date"`
	Notes           pgtype.Text    `json:"notes"`
	RecurringType   pgtype.Text    `json:"recurring_type"`
	StartDate       pgtype.Date    `json:"start_date"`
	EndDate         pgtype.Date    `json:"end_date"`
	PriorityGroupID pgtype.UUID    `json:"priority_group_id"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (BudgetExpense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.UserID,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.CategoryID,
		arg.ExpenseDate,
		arg.Notes,
		arg.RecurringType,
		arg.StartDate,
		arg.EndDate,
		arg.PriorityGroupID,
	)
	var i BudgetExpense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.CategoryID,
		&i.ExpenseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
		&i.UserID,
		&i.RecurringType,
		&i.StartDate,
		&i.EndDate,
		&i.PriorityGroupID,
	)
	return i, err
}

const updateTag = `-- name: UpdateTag :one
UPDATE budget_tags
SET
    name = COALESCE($3, name),
    color = COALESCE($4, color)
WHERE id = $1 AND user_id = $2
RETURNING id, name, color, created_at, user_id
`

type UpdateTagParams struct {
	ID     uuid.UUID   `json:"id"`
	UserID uuid.UUID   `json:"user_id"`
	Name   pgtype.Text `json:"name"`
	Color  pgtype.Text `json:"color"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (BudgetTag, error) {
	row := q.db.QueryRow(ctx, updateTag,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Color,
	)
	var i BudgetTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UserID,
	)
	return i, err
}
