// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BudgetCategory struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Color     pgtype.Text      `json:"color"`
	Icon      pgtype.Text      `json:"icon"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UserID    uuid.UUID        `json:"user_id"`
}

type BudgetExpense struct {
	ID          uuid.UUID        `json:"id"`
	Description string           `json:"description"`
	Amount      pgtype.Numeric   `json:"amount"`
	Currency    pgtype.Text      `json:"currency"`
	CategoryID  pgtype.UUID      `json:"category_id"`
	ExpenseDate pgtype.Date      `json:"expense_date"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Notes       pgtype.Text      `json:"notes"`
	UserID      uuid.UUID        `json:"user_id"`
}

type BudgetExpenseTag struct {
	ExpenseID uuid.UUID `json:"expense_id"`
	TagID     uuid.UUID `json:"tag_id"`
}

type BudgetIncome struct {
	ID            uuid.UUID        `json:"id"`
	UserID        uuid.UUID        `json:"user_id"`
	Amount        pgtype.Numeric   `json:"amount"`
	Currency      pgtype.Text      `json:"currency"`
	Date          pgtype.Date      `json:"date"`
	Description   pgtype.Text      `json:"description"`
	RecurringType pgtype.Text      `json:"recurring_type"`
	StartDate     pgtype.Date      `json:"start_date"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	EndDate       pgtype.Date      `json:"end_date"`
}

type BudgetTag struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Color     pgtype.Text      `json:"color"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UserID    uuid.UUID        `json:"user_id"`
}

type Service struct {
	ID                  uuid.UUID        `json:"id"`
	Name                string           `json:"name"`
	Url                 string           `json:"url"`
	Icon                pgtype.Text      `json:"icon"`
	Description         pgtype.Text      `json:"description"`
	ServiceType         pgtype.Text      `json:"service_type"`
	HealthCheckInterval pgtype.Int4      `json:"health_check_interval"`
	HealthCheckMethod   pgtype.Text      `json:"health_check_method"`
	ExpectedStatusCodes []int32          `json:"expected_status_codes"`
	Timeout             pgtype.Int4      `json:"timeout"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	IsActive            pgtype.Bool      `json:"is_active"`
}

type ServiceHealthHistory struct {
	ID           uuid.UUID        `json:"id"`
	ServiceID    pgtype.UUID      `json:"service_id"`
	Status       string           `json:"status"`
	ResponseTime pgtype.Int4      `json:"response_time"`
	StatusCode   pgtype.Int4      `json:"status_code"`
	ErrorMessage pgtype.Text      `json:"error_message"`
	CheckedAt    pgtype.Timestamp `json:"checked_at"`
}

type Session struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	TokenHash string           `json:"token_hash"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID           uuid.UUID        `json:"id"`
	Email        string           `json:"email"`
	PasswordHash pgtype.Text      `json:"password_hash"`
	Role         string           `json:"role"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
