// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Expense Tags
	AddExpenseTag(ctx context.Context, arg AddExpenseTagParams) error
	CheckSkippedExpense(ctx context.Context, arg CheckSkippedExpenseParams) (bool, error)
	CheckSkippedIncome(ctx context.Context, arg CheckSkippedIncomeParams) (bool, error)
	CountActiveSessions(ctx context.Context) (int64, error)
	CountAdmins(ctx context.Context) (int64, error)
	CountExpenses(ctx context.Context, arg CountExpensesParams) (int64, error)
	CountIncomes(ctx context.Context, arg CountIncomesParams) (int64, error)
	CountSearchExpenses(ctx context.Context, arg CountSearchExpensesParams) (int64, error)
	// Categories
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (BudgetCategory, error)
	// Category Budgets
	CreateCategoryBudget(ctx context.Context, arg CreateCategoryBudgetParams) (CategoryBudget, error)
	// Expenses
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (BudgetExpense, error)
	CreateHealthHistory(ctx context.Context, arg CreateHealthHistoryParams) (ServiceHealthHistory, error)
	// Incomes
	CreateIncome(ctx context.Context, arg CreateIncomeParams) (BudgetIncome, error)
	// Savings Goals
	CreateSavingsGoal(ctx context.Context, arg CreateSavingsGoalParams) (SavingsGoal, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	// Sessions
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Tags
	CreateTag(ctx context.Context, arg CreateTagParams) (BudgetTag, error)
	// Users
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	DeleteCategoryBudget(ctx context.Context, arg DeleteCategoryBudgetParams) error
	DeleteExpense(ctx context.Context, arg DeleteExpenseParams) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteIncome(ctx context.Context, arg DeleteIncomeParams) error
	DeleteSavingsGoal(ctx context.Context, arg DeleteSavingsGoalParams) error
	DeleteService(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	DeleteTag(ctx context.Context, arg DeleteTagParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserSessions(ctx context.Context, userID uuid.UUID) error
	ExportExpenses(ctx context.Context, userID uuid.UUID) ([]ExportExpensesRow, error)
	ExportIncomes(ctx context.Context, userID uuid.UUID) ([]BudgetIncome, error)
	GetAllCategorySpending(ctx context.Context, arg GetAllCategorySpendingParams) ([]GetAllCategorySpendingRow, error)
	GetAllOneTimeIncomeToDate(ctx context.Context, arg GetAllOneTimeIncomeToDateParams) (interface{}, error)
	GetAllRecurringIncomeRules(ctx context.Context, arg GetAllRecurringIncomeRulesParams) ([]BudgetIncome, error)
	GetAllServicesStats(ctx context.Context) (GetAllServicesStatsRow, error)
	GetAllTotalExpensesToDate(ctx context.Context, arg GetAllTotalExpensesToDateParams) (interface{}, error)
	GetAllTotalSpending(ctx context.Context, arg GetAllTotalSpendingParams) (GetAllTotalSpendingRow, error)
	GetBudgetVariance(ctx context.Context, arg GetBudgetVarianceParams) ([]GetBudgetVarianceRow, error)
	GetCategory(ctx context.Context, arg GetCategoryParams) (BudgetCategory, error)
	GetCategoryBudget(ctx context.Context, arg GetCategoryBudgetParams) (CategoryBudget, error)
	GetCategoryBudgetByCategoryAndMonth(ctx context.Context, arg GetCategoryBudgetByCategoryAndMonthParams) (CategoryBudget, error)
	GetCategoryByID(ctx context.Context, id uuid.UUID) (BudgetCategory, error)
	GetCategorySpending(ctx context.Context, arg GetCategorySpendingParams) ([]GetCategorySpendingRow, error)
	GetDailySpending(ctx context.Context, arg GetDailySpendingParams) ([]GetDailySpendingRow, error)
	// Spending Velocity & Trends
	GetDailySpendingForVelocity(ctx context.Context, arg GetDailySpendingForVelocityParams) ([]GetDailySpendingForVelocityRow, error)
	GetExpense(ctx context.Context, arg GetExpenseParams) (BudgetExpense, error)
	GetExpenseByID(ctx context.Context, id uuid.UUID) (BudgetExpense, error)
	GetExpenseRowsForPeriod(ctx context.Context, arg GetExpenseRowsForPeriodParams) ([]BudgetExpense, error)
	GetExpenseTags(ctx context.Context, expenseID uuid.UUID) ([]BudgetTag, error)
	// Statistics (filtered by user)
	GetExpensesByDateRange(ctx context.Context, arg GetExpensesByDateRangeParams) ([]BudgetExpense, error)
	GetExpensesForPeriod(ctx context.Context, arg GetExpensesForPeriodParams) (interface{}, error)
	GetIncome(ctx context.Context, arg GetIncomeParams) (BudgetIncome, error)
	GetIncomeByID(ctx context.Context, id uuid.UUID) (BudgetIncome, error)
	// Savings Rate Calculation
	GetIncomeForPeriod(ctx context.Context, arg GetIncomeForPeriodParams) (interface{}, error)
	GetIncomeRowsForPeriod(ctx context.Context, arg GetIncomeRowsForPeriodParams) ([]BudgetIncome, error)
	GetMerchantSpendingTrend(ctx context.Context, arg GetMerchantSpendingTrendParams) ([]GetMerchantSpendingTrendRow, error)
	GetMonthToDateSpending(ctx context.Context, arg GetMonthToDateSpendingParams) (GetMonthToDateSpendingRow, error)
	GetMonthlySpending(ctx context.Context, userID uuid.UUID) ([]GetMonthlySpendingRow, error)
	// Budget Remaining Calculation Queries
	// These queries fetch raw data; proration logic is handled in the application layer
	GetOneTimeIncomeToDate(ctx context.Context, arg GetOneTimeIncomeToDateParams) (interface{}, error)
	GetOneTimeIncomesForPeriod(ctx context.Context, arg GetOneTimeIncomesForPeriodParams) ([]BudgetIncome, error)
	GetPriorityGroupBySlug(ctx context.Context, slug string) (BudgetPriorityGroup, error)
	GetRecurringIncomeForPeriod(ctx context.Context, arg GetRecurringIncomeForPeriodParams) ([]BudgetIncome, error)
	GetRecurringIncomeRules(ctx context.Context, arg GetRecurringIncomeRulesParams) ([]BudgetIncome, error)
	GetSavingsGoal(ctx context.Context, arg GetSavingsGoalParams) (SavingsGoal, error)
	GetSavingsGoalsSummary(ctx context.Context, userID uuid.UUID) (GetSavingsGoalsSummaryRow, error)
	GetService(ctx context.Context, id uuid.UUID) (Service, error)
	GetServiceHistory(ctx context.Context, arg GetServiceHistoryParams) ([]ServiceHealthHistory, error)
	GetServiceStats24h(ctx context.Context, serviceID pgtype.UUID) (GetServiceStats24hRow, error)
	GetServiceStats30d(ctx context.Context, serviceID pgtype.UUID) (GetServiceStats30dRow, error)
	GetServiceStats7d(ctx context.Context, serviceID pgtype.UUID) (GetServiceStats7dRow, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	GetSkippedIncomeDatesForPeriod(ctx context.Context, arg GetSkippedIncomeDatesForPeriodParams) ([]pgtype.Date, error)
	// Weekday Analysis
	GetSpendingByDayOfWeek(ctx context.Context, arg GetSpendingByDayOfWeekParams) ([]GetSpendingByDayOfWeekRow, error)
	// 50/30/20 Analysis
	GetSpendingByPriorityGroup(ctx context.Context, arg GetSpendingByPriorityGroupParams) ([]GetSpendingByPriorityGroupRow, error)
	GetTag(ctx context.Context, arg GetTagParams) (BudgetTag, error)
	GetTagByID(ctx context.Context, id uuid.UUID) (BudgetTag, error)
	// Merchant Analysis
	GetTopMerchants(ctx context.Context, arg GetTopMerchantsParams) ([]GetTopMerchantsRow, error)
	GetTotalExpensesToDate(ctx context.Context, arg GetTotalExpensesToDateParams) (interface{}, error)
	GetTotalSpending(ctx context.Context, arg GetTotalSpendingParams) (GetTotalSpendingRow, error)
	GetUnclassifiedExpenseCount(ctx context.Context, arg GetUnclassifiedExpenseCountParams) (GetUnclassifiedExpenseCountRow, error)
	// Upcoming Recurring Expenses Forecasting
	GetUpcomingRecurringExpenses(ctx context.Context, arg GetUpcomingRecurringExpensesParams) ([]GetUpcomingRecurringExpensesRow, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListActiveServicesForHealthCheck(ctx context.Context) ([]ListActiveServicesForHealthCheckRow, error)
	ListAllCategories(ctx context.Context) ([]ListAllCategoriesRow, error)
	ListAllExpenses(ctx context.Context, arg ListAllExpensesParams) ([]ListAllExpensesRow, error)
	ListAllIncomes(ctx context.Context, arg ListAllIncomesParams) ([]ListAllIncomesRow, error)
	ListAllTags(ctx context.Context) ([]ListAllTagsRow, error)
	ListCategories(ctx context.Context, userID uuid.UUID) ([]BudgetCategory, error)
	ListCategoryBudgets(ctx context.Context, arg ListCategoryBudgetsParams) ([]ListCategoryBudgetsRow, error)
	ListExpenses(ctx context.Context, arg ListExpensesParams) ([]ListExpensesRow, error)
	ListIncomes(ctx context.Context, arg ListIncomesParams) ([]BudgetIncome, error)
	// Priority Groups
	ListPriorityGroups(ctx context.Context) ([]BudgetPriorityGroup, error)
	ListSavingsGoals(ctx context.Context, userID uuid.UUID) ([]SavingsGoal, error)
	ListServices(ctx context.Context) ([]ListServicesRow, error)
	ListTags(ctx context.Context, userID uuid.UUID) ([]BudgetTag, error)
	ListUsers(ctx context.Context) ([]User, error)
	RemoveAllExpenseTags(ctx context.Context, expenseID uuid.UUID) error
	RemoveExpenseTag(ctx context.Context, arg RemoveExpenseTagParams) error
	SearchExpenses(ctx context.Context, arg SearchExpensesParams) ([]SearchExpensesRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (BudgetCategory, error)
	UpdateCategoryBudget(ctx context.Context, arg UpdateCategoryBudgetParams) (CategoryBudget, error)
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (BudgetExpense, error)
	UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (BudgetIncome, error)
	UpdateSavingsGoal(ctx context.Context, arg UpdateSavingsGoalParams) (SavingsGoal, error)
	UpdateSavingsGoalProgress(ctx context.Context, arg UpdateSavingsGoalProgressParams) (SavingsGoal, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (BudgetTag, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertSkippedExpense(ctx context.Context, arg UpsertSkippedExpenseParams) (UpsertSkippedExpenseRow, error)
	UpsertSkippedIncome(ctx context.Context, arg UpsertSkippedIncomeParams) (UpsertSkippedIncomeRow, error)
}

var _ Querier = (*Queries)(nil)
