// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: savings_goals.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSavingsGoal = `-- name: CreateSavingsGoal :one

INSERT INTO savings_goals (
    user_id, name, target_amount, current_amount, deadline, icon, color
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, name, target_amount, current_amount, deadline, icon, color, created_at, updated_at
`

type CreateSavingsGoalParams struct {
	UserID        uuid.UUID      `json:"user_id"`
	Name          string         `json:"name"`
	TargetAmount  pgtype.Numeric `json:"target_amount"`
	CurrentAmount pgtype.Numeric `json:"current_amount"`
	Deadline      pgtype.Date    `json:"deadline"`
	Icon          pgtype.Text    `json:"icon"`
	Color         pgtype.Text    `json:"color"`
}

// Savings Goals
func (q *Queries) CreateSavingsGoal(ctx context.Context, arg CreateSavingsGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, createSavingsGoal,
		arg.UserID,
		arg.Name,
		arg.TargetAmount,
		arg.CurrentAmount,
		arg.Deadline,
		arg.Icon,
		arg.Color,
	)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Deadline,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSavingsGoal = `-- name: DeleteSavingsGoal :exec
DELETE FROM savings_goals
WHERE id = $1 AND user_id = $2
`

type DeleteSavingsGoalParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteSavingsGoal(ctx context.Context, arg DeleteSavingsGoalParams) error {
	_, err := q.db.Exec(ctx, deleteSavingsGoal, arg.ID, arg.UserID)
	return err
}

const getSavingsGoal = `-- name: GetSavingsGoal :one
SELECT id, user_id, name, target_amount, current_amount, deadline, icon, color, created_at, updated_at FROM savings_goals
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetSavingsGoalParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetSavingsGoal(ctx context.Context, arg GetSavingsGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, getSavingsGoal, arg.ID, arg.UserID)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Deadline,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSavingsGoalsSummary = `-- name: GetSavingsGoalsSummary :one
SELECT 
    COUNT(*) as total_goals,
    COALESCE(SUM(target_amount), 0::numeric) as total_target,
    COALESCE(SUM(current_amount), 0::numeric) as total_saved,
    COUNT(CASE WHEN current_amount >= target_amount THEN 1 END) as completed_goals
FROM savings_goals
WHERE user_id = $1
`

type GetSavingsGoalsSummaryRow struct {
	TotalGoals     int64       `json:"total_goals"`
	TotalTarget    interface{} `json:"total_target"`
	TotalSaved     interface{} `json:"total_saved"`
	CompletedGoals int64       `json:"completed_goals"`
}

func (q *Queries) GetSavingsGoalsSummary(ctx context.Context, userID uuid.UUID) (GetSavingsGoalsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getSavingsGoalsSummary, userID)
	var i GetSavingsGoalsSummaryRow
	err := row.Scan(
		&i.TotalGoals,
		&i.TotalTarget,
		&i.TotalSaved,
		&i.CompletedGoals,
	)
	return i, err
}

const listSavingsGoals = `-- name: ListSavingsGoals :many
SELECT id, user_id, name, target_amount, current_amount, deadline, icon, color, created_at, updated_at FROM savings_goals
WHERE user_id = $1
ORDER BY 
    CASE WHEN deadline IS NULL THEN 1 ELSE 0 END,
    deadline ASC,
    created_at DESC
`

func (q *Queries) ListSavingsGoals(ctx context.Context, userID uuid.UUID) ([]SavingsGoal, error) {
	rows, err := q.db.Query(ctx, listSavingsGoals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavingsGoal{}
	for rows.Next() {
		var i SavingsGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TargetAmount,
			&i.CurrentAmount,
			&i.Deadline,
			&i.Icon,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSavingsGoal = `-- name: UpdateSavingsGoal :one
UPDATE savings_goals
SET
    name = COALESCE($3, name),
    target_amount = COALESCE($4, target_amount),
    current_amount = COALESCE($5, current_amount),
    deadline = COALESCE($6, deadline),
    icon = COALESCE($7, icon),
    color = COALESCE($8, color),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, target_amount, current_amount, deadline, icon, color, created_at, updated_at
`

type UpdateSavingsGoalParams struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	Name          pgtype.Text    `json:"name"`
	TargetAmount  pgtype.Numeric `json:"target_amount"`
	CurrentAmount pgtype.Numeric `json:"current_amount"`
	Deadline      pgtype.Date    `json:"deadline"`
	Icon          pgtype.Text    `json:"icon"`
	Color         pgtype.Text    `json:"color"`
}

func (q *Queries) UpdateSavingsGoal(ctx context.Context, arg UpdateSavingsGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, updateSavingsGoal,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TargetAmount,
		arg.CurrentAmount,
		arg.Deadline,
		arg.Icon,
		arg.Color,
	)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Deadline,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSavingsGoalProgress = `-- name: UpdateSavingsGoalProgress :one
UPDATE savings_goals
SET
    current_amount = $2,
    updated_at = NOW()
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, name, target_amount, current_amount, deadline, icon, color, created_at, updated_at
`

type UpdateSavingsGoalProgressParams struct {
	ID            uuid.UUID      `json:"id"`
	CurrentAmount pgtype.Numeric `json:"current_amount"`
	UserID        uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateSavingsGoalProgress(ctx context.Context, arg UpdateSavingsGoalProgressParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, updateSavingsGoalProgress, arg.ID, arg.CurrentAmount, arg.UserID)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Deadline,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
