// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createHealthHistory = `-- name: CreateHealthHistory :one
INSERT INTO service_health_history (
    service_id, status, response_time, status_code, error_message
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, service_id, status, response_time, status_code, error_message, checked_at
`

type CreateHealthHistoryParams struct {
	ServiceID    pgtype.UUID `json:"service_id"`
	Status       string      `json:"status"`
	ResponseTime pgtype.Int4 `json:"response_time"`
	StatusCode   pgtype.Int4 `json:"status_code"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) CreateHealthHistory(ctx context.Context, arg CreateHealthHistoryParams) (ServiceHealthHistory, error) {
	row := q.db.QueryRow(ctx, createHealthHistory,
		arg.ServiceID,
		arg.Status,
		arg.ResponseTime,
		arg.StatusCode,
		arg.ErrorMessage,
	)
	var i ServiceHealthHistory
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Status,
		&i.ResponseTime,
		&i.StatusCode,
		&i.ErrorMessage,
		&i.CheckedAt,
	)
	return i, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (
    name, url, icon, description, service_type,
    health_check_interval, health_check_method,
    expected_status_codes, timeout
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, name, url, icon, description, service_type, health_check_interval, health_check_method, expected_status_codes, timeout, created_at, updated_at, is_active
`

type CreateServiceParams struct {
	Name                string      `json:"name"`
	Url                 string      `json:"url"`
	Icon                pgtype.Text `json:"icon"`
	Description         pgtype.Text `json:"description"`
	ServiceType         pgtype.Text `json:"service_type"`
	HealthCheckInterval pgtype.Int4 `json:"health_check_interval"`
	HealthCheckMethod   pgtype.Text `json:"health_check_method"`
	ExpectedStatusCodes []int32     `json:"expected_status_codes"`
	Timeout             pgtype.Int4 `json:"timeout"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Name,
		arg.Url,
		arg.Icon,
		arg.Description,
		arg.ServiceType,
		arg.HealthCheckInterval,
		arg.HealthCheckMethod,
		arg.ExpectedStatusCodes,
		arg.Timeout,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Icon,
		&i.Description,
		&i.ServiceType,
		&i.HealthCheckInterval,
		&i.HealthCheckMethod,
		&i.ExpectedStatusCodes,
		&i.Timeout,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services
WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getAllServicesStats = `-- name: GetAllServicesStats :one
SELECT 
    COUNT(DISTINCT service_id) as total_services,
    COUNT(*) as total_checks,
    COUNT(CASE WHEN status = 'online' THEN 1 END) as successful_checks,
    COALESCE(AVG(CASE WHEN response_time IS NOT NULL THEN response_time ELSE 0 END), 0) as avg_response_time
FROM service_health_history
WHERE checked_at >= NOW() - INTERVAL '24 hours'
`

type GetAllServicesStatsRow struct {
	TotalServices    int64       `json:"total_services"`
	TotalChecks      int64       `json:"total_checks"`
	SuccessfulChecks int64       `json:"successful_checks"`
	AvgResponseTime  interface{} `json:"avg_response_time"`
}

func (q *Queries) GetAllServicesStats(ctx context.Context) (GetAllServicesStatsRow, error) {
	row := q.db.QueryRow(ctx, getAllServicesStats)
	var i GetAllServicesStatsRow
	err := row.Scan(
		&i.TotalServices,
		&i.TotalChecks,
		&i.SuccessfulChecks,
		&i.AvgResponseTime,
	)
	return i, err
}

const getService = `-- name: GetService :one
SELECT id, name, url, icon, description, service_type, health_check_interval, health_check_method, expected_status_codes, timeout, created_at, updated_at, is_active FROM services
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetService(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Icon,
		&i.Description,
		&i.ServiceType,
		&i.HealthCheckInterval,
		&i.HealthCheckMethod,
		&i.ExpectedStatusCodes,
		&i.Timeout,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const getServiceHistory = `-- name: GetServiceHistory :many
SELECT id, service_id, status, response_time, status_code, error_message, checked_at FROM service_health_history
WHERE service_id = $1
ORDER BY checked_at DESC
LIMIT $2
`

type GetServiceHistoryParams struct {
	ServiceID pgtype.UUID `json:"service_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) GetServiceHistory(ctx context.Context, arg GetServiceHistoryParams) ([]ServiceHealthHistory, error) {
	rows, err := q.db.Query(ctx, getServiceHistory, arg.ServiceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceHealthHistory{}
	for rows.Next() {
		var i ServiceHealthHistory
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Status,
			&i.ResponseTime,
			&i.StatusCode,
			&i.ErrorMessage,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceStats24h = `-- name: GetServiceStats24h :one
SELECT 
    COUNT(*) as total_checks,
    COUNT(CASE WHEN status = 'online' THEN 1 END) as successful_checks,
    COALESCE(AVG(CASE WHEN response_time IS NOT NULL THEN response_time ELSE 0 END), 0) as avg_response_time
FROM service_health_history
WHERE service_id = $1 AND checked_at >= NOW() - INTERVAL '24 hours'
`

type GetServiceStats24hRow struct {
	TotalChecks      int64       `json:"total_checks"`
	SuccessfulChecks int64       `json:"successful_checks"`
	AvgResponseTime  interface{} `json:"avg_response_time"`
}

func (q *Queries) GetServiceStats24h(ctx context.Context, serviceID pgtype.UUID) (GetServiceStats24hRow, error) {
	row := q.db.QueryRow(ctx, getServiceStats24h, serviceID)
	var i GetServiceStats24hRow
	err := row.Scan(&i.TotalChecks, &i.SuccessfulChecks, &i.AvgResponseTime)
	return i, err
}

const getServiceStats30d = `-- name: GetServiceStats30d :one
SELECT 
    COUNT(*) as total_checks,
    COUNT(CASE WHEN status = 'online' THEN 1 END) as successful_checks
FROM service_health_history
WHERE service_id = $1 AND checked_at >= NOW() - INTERVAL '30 days'
`

type GetServiceStats30dRow struct {
	TotalChecks      int64 `json:"total_checks"`
	SuccessfulChecks int64 `json:"successful_checks"`
}

func (q *Queries) GetServiceStats30d(ctx context.Context, serviceID pgtype.UUID) (GetServiceStats30dRow, error) {
	row := q.db.QueryRow(ctx, getServiceStats30d, serviceID)
	var i GetServiceStats30dRow
	err := row.Scan(&i.TotalChecks, &i.SuccessfulChecks)
	return i, err
}

const getServiceStats7d = `-- name: GetServiceStats7d :one
SELECT 
    COUNT(*) as total_checks,
    COUNT(CASE WHEN status = 'online' THEN 1 END) as successful_checks
FROM service_health_history
WHERE service_id = $1 AND checked_at >= NOW() - INTERVAL '7 days'
`

type GetServiceStats7dRow struct {
	TotalChecks      int64 `json:"total_checks"`
	SuccessfulChecks int64 `json:"successful_checks"`
}

func (q *Queries) GetServiceStats7d(ctx context.Context, serviceID pgtype.UUID) (GetServiceStats7dRow, error) {
	row := q.db.QueryRow(ctx, getServiceStats7d, serviceID)
	var i GetServiceStats7dRow
	err := row.Scan(&i.TotalChecks, &i.SuccessfulChecks)
	return i, err
}

const listActiveServicesForHealthCheck = `-- name: ListActiveServicesForHealthCheck :many
SELECT id, name, url, health_check_method, expected_status_codes, timeout
FROM services
WHERE is_active = true
`

type ListActiveServicesForHealthCheckRow struct {
	ID                  uuid.UUID   `json:"id"`
	Name                string      `json:"name"`
	Url                 string      `json:"url"`
	HealthCheckMethod   pgtype.Text `json:"health_check_method"`
	ExpectedStatusCodes []int32     `json:"expected_status_codes"`
	Timeout             pgtype.Int4 `json:"timeout"`
}

func (q *Queries) ListActiveServicesForHealthCheck(ctx context.Context) ([]ListActiveServicesForHealthCheckRow, error) {
	rows, err := q.db.Query(ctx, listActiveServicesForHealthCheck)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveServicesForHealthCheckRow{}
	for rows.Next() {
		var i ListActiveServicesForHealthCheckRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.HealthCheckMethod,
			&i.ExpectedStatusCodes,
			&i.Timeout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT 
    s.id, s.name, s.url, s.icon, s.description, s.service_type, s.health_check_interval, s.health_check_method, s.expected_status_codes, s.timeout, s.created_at, s.updated_at, s.is_active,
    COALESCE(h.status, 'unknown') as current_status,
    h.checked_at as last_check,
    h.response_time
FROM services s
LEFT JOIN LATERAL (
    SELECT status, checked_at, response_time
    FROM service_health_history
    WHERE service_id = s.id
    ORDER BY checked_at DESC
    LIMIT 1
) h ON true
WHERE s.is_active = true
ORDER BY s.name
`

type ListServicesRow struct {
	ID                  uuid.UUID        `json:"id"`
	Name                string           `json:"name"`
	Url                 string           `json:"url"`
	Icon                pgtype.Text      `json:"icon"`
	Description         pgtype.Text      `json:"description"`
	ServiceType         pgtype.Text      `json:"service_type"`
	HealthCheckInterval pgtype.Int4      `json:"health_check_interval"`
	HealthCheckMethod   pgtype.Text      `json:"health_check_method"`
	ExpectedStatusCodes []int32          `json:"expected_status_codes"`
	Timeout             pgtype.Int4      `json:"timeout"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	IsActive            pgtype.Bool      `json:"is_active"`
	CurrentStatus       string           `json:"current_status"`
	LastCheck           pgtype.Timestamp `json:"last_check"`
	ResponseTime        pgtype.Int4      `json:"response_time"`
}

func (q *Queries) ListServices(ctx context.Context) ([]ListServicesRow, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesRow{}
	for rows.Next() {
		var i ListServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Icon,
			&i.Description,
			&i.ServiceType,
			&i.HealthCheckInterval,
			&i.HealthCheckMethod,
			&i.ExpectedStatusCodes,
			&i.Timeout,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
			&i.CurrentStatus,
			&i.LastCheck,
			&i.ResponseTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET 
    name = COALESCE($1, name),
    url = COALESCE($2, url),
    icon = COALESCE($3, icon),
    description = COALESCE($4, description),
    service_type = COALESCE($5, service_type),
    health_check_interval = COALESCE($6, health_check_interval),
    health_check_method = COALESCE($7, health_check_method),
    expected_status_codes = COALESCE($8, expected_status_codes),
    timeout = COALESCE($9, timeout),
    is_active = COALESCE($10, is_active),
    updated_at = NOW()
WHERE id = $11
RETURNING id, name, url, icon, description, service_type, health_check_interval, health_check_method, expected_status_codes, timeout, created_at, updated_at, is_active
`

type UpdateServiceParams struct {
	Name                pgtype.Text `json:"name"`
	Url                 pgtype.Text `json:"url"`
	Icon                pgtype.Text `json:"icon"`
	Description         pgtype.Text `json:"description"`
	ServiceType         pgtype.Text `json:"service_type"`
	HealthCheckInterval pgtype.Int4 `json:"health_check_interval"`
	HealthCheckMethod   pgtype.Text `json:"health_check_method"`
	ExpectedStatusCodes []int32     `json:"expected_status_codes"`
	Timeout             pgtype.Int4 `json:"timeout"`
	IsActive            pgtype.Bool `json:"is_active"`
	ID                  uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.Name,
		arg.Url,
		arg.Icon,
		arg.Description,
		arg.ServiceType,
		arg.HealthCheckInterval,
		arg.HealthCheckMethod,
		arg.ExpectedStatusCodes,
		arg.Timeout,
		arg.IsActive,
		arg.ID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Icon,
		&i.Description,
		&i.ServiceType,
		&i.HealthCheckInterval,
		&i.HealthCheckMethod,
		&i.ExpectedStatusCodes,
		&i.Timeout,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}
