---
image:
  repository: rancher/local-path-provisioner
  tag: v0.0.34
  pullPolicy: IfNotPresent

storageClass:
  create: true
  name: local-path
  defaultClass: false
  defaultVolumeType: hostPath
  reclaimPolicy: Retain
  volumeBindingMode: WaitForFirstConsumer

nodePathMap:
  - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
    paths:
      - /opt/local-path-provisioner

securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  readOnlyRootFilesystem: true

# resources:
#   limits:
#     cpu: 200m
#     memory: 128Mi
#   requests:
#     cpu: 50m
#     memory: 64Mi

rbac:
  create: true

serviceAccount:
  create: true

configmap:
  name: local-path-config
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod:
    name: "helper-pod"
    priorityClassName: "system-node-critical"
