apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-world
  namespace: hello-world
spec:
  parentRefs:
    - name: gateway-external # must match Gateway's metadata.name
      namespace: gateway
      sectionName: https # must match Gateway's listeners[].name
  hostnames:
    - "hello-world.ejsadiarin.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: hello-world
          port: 8080
