---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - namespace.yaml
  - pvc.yaml
# - ../../common/cilium-network-policies

labels:
  - pairs:
      app.kubernetes.io/name: hello-world
      app.kubernetes.io/part-of: web-apps
      app.kubernetes.io/managed-by: argocd
