apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-world-local
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
